### ISSUE TITLE
How to decrypt apps?

### ISSUE THREAD

**Issue by DarkShadow44** [hikari-no-yume/touchHLE#100]
Sorry if I missed it, but how do I get a decrypted app?

I still have old .ipa files from my old iPod, but those are encrypted and give the expected error
`Could not load executable: The executable is encrypted. touchHLE can't run encrypted apps`

I still have my jailbroken iPod with iOS4, any tips for decrypting?

**Comment by hikari-no-yume** [comment]
I've found Crackulous to work fine for decrypting apps on my jailbroken iOS 4 device. You can get it from the Cydia repo `http://pwnage.dev/`. You'll also need some kind of file transfer tool so you can get the decrypted apps off the device. Personally I just used SSH.

Good luck!

**Comment by DarkShadow44** [comment]
Thanks, that worked like a charm! Sadly my Apps don't work yet, but maybe one day I learn rust and can play around with the code. Thanks for the project!
