### ISSUE TITLE
failed to run custom build command for `sdl2-sys v0.35.2

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#102]
error: failed to run custom build command for `sdl2-sys v0.35.2 (https://github.com/hikari-no-yume/rust-sdl2.git?branch=update-bundled-SDL2#571085ae)`

**Comment by hikari-no-yume** [comment]
duplicate of https://github.com/hikari-no-yume/touchHLE/issues/103 (?)
