### ISSUE TITLE
error: failed to run custom build command for `sdl2-sys v0.35.2

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#103]
**error: failed to run custom build command for `sdl2-sys v0.35.2 (https://github.com/hikari-no-yume/rust-sdl2.git?branch=update-bundled-SDL2#571085ae)`**

I have tried to install the sdl2 following your docs, but still shows the error.

platform is msvc+clion+windows11

**Comment by hikari-no-yume** [comment]
Please provide the full error message.

**Comment by ghost** [comment]
Sorry, I'm new to GitHub and accidentally created duplicate issues. The complete error message was about an abnormal CMake configuration (prompting whether CMake is installed properly, but it was indeed installed). Finally, I switched the build toolchain from VS to MinGW and the compilation was successful.

**Comment by hikari-no-yume** [comment]
Huh, that's interesting. It works for me with MSVC, but I'm on Windows 10 and probably not using the same MSVC version as you.

**Comment by ghost** [comment]
Not only that, building the project using the 'build project' menu in CLion would result in failure. However, entering 'cargo build' in the terminal would succeed and the software could be used normally.

**Comment by hikari-no-yume** [comment]
Huh. Can you find out what sequence of commands CLion is running?

**Comment by ghost** [comment]
sorry, I am just a beginner in the rust and the clion, so I don't know how to get it.
