### ISSUE TITLE
PVRTC Texture support

### ISSUE THREAD

**Issue by klaxons1** [hikari-no-yume/touchHLE#106]
Well, iPhone uses powerVR video accelerators. This means that some games use PVRTC compression for textures. This compression is only supported by PowerVR gpu's. So, you should implement software decoder for this texture format.
You can use that for reference I guess: https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/drivers/src/graphics/backend/ogl/pvrt-dec.cpp

**Comment by hikari-no-yume** [comment]
Anything in particular that prompted this issue? I'll of course add PVRTC decompression once I have a game that needs it.

**Comment by hikari-no-yume** [comment]
As it happens, a game I'm currently trying to get working needs this, so I've done it: c8c0e2f1785806dfd079e9422b6011dbb7b5bce4.

I used the unmodified version from Imagination's SDK. I'm comfortable with the provenance of that code. It doesn't support PVRTC2, but I believe that was introduced in late 2012, so it'll probably be a long time before we are able to support apps that would need it anyway.

**Comment by klaxons1** [comment]
I'm glad that emulator is getting better very quickly.
Good luck, hikari-no-yume!
