### ISSUE TITLE
Android Studio Build ERROR

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#108]
I get error java.lang.ClassNotFoundException: org.bouncycastle.operator.OperatorCreationException of build in Android Studio

My os: Windows 10 Pro 2004
Android Studio Electric Eel | 2022.1.1 Patch 2
Android NDK 25.2.9519653

what to do?)

**Comment by hikari-no-yume** [comment]
I have no idea, sorry. Did you follow the instructions?

**Comment by ghost** [comment]
> I have no idea, sorry. Did you follow the instructions?

yes

**Comment by hikari-no-yume** [comment]
Did you try to build it for Windows first?

**Comment by ghost** [comment]
> Did you try to build it for Windows first?

no, only for android

**Comment by hikari-no-yume** [comment]
Our Android build instructions clearly state:

> Make sure you can build and run touchHLE desktop version first

**Comment by ghost** [comment]
> Our Android build instructions clearly state:
> 
> > Make sure you can build and run touchHLE desktop version first

it seems I just didn't notice, now I'll try)

**Comment by ghost** [comment]
I build for windows, but i still get this error

**Comment by ghost** [comment]
can you build for me? I just really want to try this emulator

**Comment by hikari-no-yume** [comment]
I don't want to provide Android builds right now because it's not quite ready, but I'm planning on making an Android release later this month. If you want to get a Discord notification when that happens: https://discord.gg/sVMXc8z3eS.

**Comment by ghost** [comment]
ok
