### ISSUE TITLE
Windows Build ERROR 

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#109]
I get error about cmake but i installed it

Logs: https://pastebin.com/raw/yHz1P1gQ

**Comment by ghost** [comment]
ok i get new error 

https://pastebin.com/raw/D6vxV1Wg

visual studio is installed

**Comment by hikari-no-yume** [comment]
You probably don't have cmake in your PATH environment variable?

**Comment by ghost** [comment]
> You probably don't have cmake in your PATH environment variable?

he is there, I already have another problem

**Comment by hikari-no-yume** [comment]
Ah sorry, that was re: your first comment but we posted at almost the same time.

Re: your new error, that's weird… what components of Visual Studio do you have installed, and which version?

**Comment by ghost** [comment]
> Ah sorry, that was re: your first comment but we posted at almost the same time.
> 
> Re: your new error, that's weird… what components of Visual Studio do you have installed, and which version?

Visual Studio 2019, c++ classic apps development only

**Comment by hikari-no-yume** [comment]
Huh. That sounds like the exact set of tools touchHLE would need. Hmm…

I'm lost, to be honest, but I found this StackOverflow answer: https://stackoverflow.com/a/52530486

Does it help at all? If at some point you get some sort of window that lists what features/tools you have installed, please post a screenshot.

**Comment by ghost** [comment]
> Huh. That sounds like the exact set of tools touchHLE would need. Hmm…
> 
> I'm lost, to be honest, but I found this StackOverflow answer: https://stackoverflow.com/a/52530486
> 
> Does it help at all? If at some point you get some sort of window that lists what features/tools you have installed, please post a screenshot.

I'm going to try visual studio 2022 download now, If that doesn't help, I'll try what you sent me.

**Comment by hikari-no-yume** [comment]
FWIW I don't think I'm using 2022. One moment, I'll check what I _am_ using…

**Comment by hikari-no-yume** [comment]
Oh, sorry, turns out I am using Visual Studio 2022 after all. Here's the stuff I have installed:

![image](https://user-images.githubusercontent.com/579774/236783711-804064f9-a828-41d0-bd58-fe2c35f758b6.png)

This is found in Tools > Get Tools and Features.

**Comment by ghost** [comment]
> Oh, sorry, turns out I am using Visual Studio 2022 after all. Here's the stuff I have installed:
> 
> ![image](https://user-images.githubusercontent.com/579774/236783711-804064f9-a828-41d0-bd58-fe2c35f758b6.png)
> 
> This is found in Tools > Get Tools and Features.

Thanks, I'm starting the installation now

**Comment by ghost** [comment]
https://pastebin.com/raw/L0Ea6cAN again new error

**Comment by ghost** [comment]
I didn't quite understand the Boost installation.

**Comment by hikari-no-yume** [comment]
What I wrote in `BUILDING.md` was:

> There is one special external dependency, Boost:
>
> * On Windows, download it from https://www.boost.org/users/download/ and extract the contents of the directory with a name like `boost_1_81_0` to `vendor/boost`.

I guess my writing was a bit unclear. You need to download one of the ZIP files from there, extract the folder inside, then move it to touchHLE's `vendor` directory and rename it to `boost`.

**Comment by ghost** [comment]
> 

ok, thanks

**Comment by ghost** [comment]
Thanks, the build is working

**Comment by hikari-no-yume** [comment]
Glad I could help!

**Comment by ciciplusplus** [comment]
I also need to add path to `cmake` installed with VS to PATH env var to make it work with a RustRover
