### ISSUE TITLE
Some windows compilation help for actions

### ISSUE THREAD

**Issue by Spidy123222** [hikari-no-yume/touchHLE#117]
I’m currently making a actions that cross compiles for this project using a Mac and I’m hitting into a issue when using the x86_64-pc-windows-gnu tool chain where it can’t find a native library for openal. I think it could Be needing OpenAl32 but it isn’t using it. This action also adds Linux but haven’t gotten to that part fully yet. This is what it looks like in the actions. I’m not exactly too good with rust so this could just be lack of knowledge here. https://github.com/Spidy123222/touchHLE/actions/runs/5100864035/jobs/9169389209#step:11:43

I’m doing this because it would make it a bit quick to compile since it can share cache with the instance. Also since this is a problem it can help with cross compilation issues.

**Comment by hikari-no-yume** [comment]
If you edit `src/audio/openal_soft_wrapper/build.rs` so it links `openal` instead of `OpenAL32`, does that fix it? There's a conditional currently because the library has a different name on Windows for some reason, but maybe it doesn't use that name when building with the GNU toolchain?

By the way, it's probably not a good idea to use a Mac for cross-compilation in GitHub Actions, since GitHub charges more for those than it does for Linux machines. Within the free quota, this means the quota is used up much more quickly when using a Mac.

**Comment by Spidy123222** [comment]
From what I look up you only need to pay if you are wanting to use above the storage they specify. And have set minutes per month. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

I'll try that out, I actually thought it was using normal openal by the looks of the message.

**Comment by hikari-no-yume** [comment]
Oh, I didn't know it was unlimited(?) for public repos. That explains why touchHLE didn't hit the minutes limit yet.

**Comment by Spidy123222** [comment]
> Oh, I didn't know it was unlimited(?) for public repos. That explains why touchHLE didn't hit the minutes limit yet.

Yeah our project at sidestore would of hit it since some compile times were 55 minutes before for a few weeks close of every day twice which would of ate it for dinner.

Looks like it didn't solve it. I'll try OpenAL32 but forced. https://github.com/Spidy123222/touchHLE/actions/runs/5106472117/jobs/9178692059

Looking at crate I do notice there's a openAL for rust bindings called allen. Maybe it can solve openal problems with cross compile and maybe not have the wrapper not care for what version openal? https://crates.io/crates/allen

**Comment by hikari-no-yume** [comment]
touchHLE uses its own wrapper package because it needs the normal OpenAL API, not high-level Rust bindings. The package you've linked builds OpenAL Soft in the same way as touchHLE's package does and would run into the same problems.

**Comment by Spidy123222** [comment]
So I guess it got past it but it had a linking error so I think I'll give this up until I find why it's having issues.
