### ISSUE TITLE
Dedicated compatibility page

### ISSUE THREAD

**Issue by Spidy123222** [hikari-no-yume/touchHLE#121]
Having a dedicated compatibility page will make it easier to find games that work or don't. Some put it on their sites like xemu, pcsx2 and dolphin. But there's also others that use GitHub to track like play! and Xenia. Having it in a page you can find what's compatible in certain ratings and able to track issues could help with the process of finding issues. 
Suggested status tags could be.

I'm highly basing this on xemu's compatibility tracker.

Broken = Doesn't boot
Intro = gets to splash screen or intro videos but not menus.
Starts = can go to menu and likely in-game but blocked by a bug or crash
Playable = game is able to be used all the way but has bugs.
Perfect = everything works and no issues.

**Comment by hikari-no-yume** [comment]
touchHLE already has a dedicated list of supported apps.

**Comment by AshthorneGaming** [comment]
If it helps, I do have this
https://docs.google.com/spreadsheets/d/1vv0YxU_GsX7Zk7XpSR3fQkWu4YYfHdRgghudDKCan4Q/edit?usp=sharing

**Comment by Spidy123222** [comment]
> touchHLE already has a dedicated list of supported apps.

Problem is it's just a md file. It would be hard to find compatibility for one game if it starts having thousands of games. It's more realistic to have a GitHub repo or a page to find and report issues of certain games.

**Comment by Spidy123222** [comment]
> If it helps, I do have this
> 
> https://docs.google.com/spreadsheets/d/1vv0YxU_GsX7Zk7XpSR3fQkWu4YYfHdRgghudDKCan4Q/edit?usp=sharing 

This is a good start I feel and is somthing like this I was thinking but more of a public page or way to report game specific issues.

**Comment by hikari-no-yume** [comment]
> Problem is it's just a md file. It would be hard to find compatibility for one game if it starts having thousands of games. 

Well, there's no urgency in solving a problem that doesn't exist yet. The status quo is that touchHLE supports a handful of games.
