### ISSUE TITLE
Linux Mint Android Build ERROR

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#124]
I get a Execution failed for task ':app:buildCargoNdkDebug'.
> Failed to run `cargo --version`. You probably don't have 'cargo' executable in PATH: /app/bin:/usr/bin:

But i have a cargo in path

**Comment by ghost** [comment]
I checked /usr/bin and find the cargo

**Comment by ghost** [comment]
![Снимок экрана от 2023-06-09 18-10-17](https://github.com/hikari-no-yume/touchHLE/assets/80280426/54f2537b-512c-4466-92cb-74fb05b5c862)

**Comment by hikari-no-yume** [comment]
I don't know what's wrong, but given the symptoms this probably isn't our fault and I'm not going to try to debug it for you, sorry.
