### ISSUE TITLE
Ubuntu broken build

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#125]
i get more errors

for example:

  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:118:38: warning: left operand of comma operator has no effect [-Wunused-value]
    118 |         value = mcl::bit::set_bit<2>(value, OFC_);
        |                                      ^~~~~
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h: In member function ‘bool Dynarmic::FP::FPSR::DZC() const’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:123:26: error: template argument 2 is invalid
    123 |         return mcl::bit::get_bit<1>(value);
        |                          ^~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h: In member function ‘void Dynarmic::FP::FPSR::DZC(bool)’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:128:27: error: ‘set_bit’ is not a member of ‘mcl::bit’; did you mean ‘get_bit’?
    128 |         value = mcl::bit::set_bit<1>(value, DZC_);
        |                           ^~~~~~~
        |                           get_bit
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:128:38: warning: left operand of comma operator has no effect [-Wunused-value]
    128 |         value = mcl::bit::set_bit<1>(value, DZC_);
        |                                      ^~~~~
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h: In member function ‘bool Dynarmic::FP::FPSR::IOC() const’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:133:26: error: template argument 2 is invalid
    133 |         return mcl::bit::get_bit<0>(value);
        |                          ^~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h: In member function ‘void Dynarmic::FP::FPSR::IOC(bool)’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:138:27: error: ‘set_bit’ is not a member of ‘mcl::bit’; did you mean ‘get_bit’?
    138 |         value = mcl::bit::set_bit<0>(value, IOC_);
        |                           ^~~~~~~
        |                           get_bit
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/fpsr.h:138:38: warning: left operand of comma operator has no effect [-Wunused-value]
    138 |         value = mcl::bit::set_bit<0>(value, IOC_);
        |                                      ^~~~~
  In file included from /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/info.h:8,
                   from /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/common/fp/op/FPMulAdd.cpp:13:
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp: At global scope:
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:15:10: error: ‘BitIntegral’ has not been declared
     15 | template<BitIntegral T>
        |          ^~~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:16:26: error: ‘T’ was not declared in this scope
     16 | inline size_t count_ones(T x)
        |                          ^
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:16:30: error: expected ‘;’ before ‘{’ token
     16 | inline size_t count_ones(T x)
        |                              ^
        |                              ;
     17 | {
        | ~                             
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:21:10: error: ‘BitIntegral’ has not been declared
     21 | template<BitIntegral T>
        |          ^~~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:22:38: error: ‘T’ was not declared in this scope
     22 | constexpr size_t count_leading_zeros(T x)
        |                                      ^
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:22:42: error: expected ‘;’ before ‘{’ token
     22 | constexpr size_t count_leading_zeros(T x)
        |                                          ^
        |                                          ;
     23 | {
        | ~                                         
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:32:10: error: ‘BitIntegral’ has not been declared
     32 | template<BitIntegral T>
        |          ^~~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:33:31: error: ‘T’ was not declared in this scope
     33 | constexpr int highest_set_bit(T x)
        |                               ^
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:33:35: error: expected ‘;’ before ‘{’ token
     33 | constexpr int highest_set_bit(T x)
        |                                   ^
        |                                   ;
     34 | {
        | ~                                  
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:43:10: error: ‘BitIntegral’ has not been declared
     43 | template<BitIntegral T>
        |          ^~~~~~~~~~~
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:44:33: error: ‘T’ was not declared in this scope
     44 | constexpr size_t lowest_set_bit(T x)
        |                                 ^
  /home/denik/touchHLE/vendor/dynarmic/externals/mcl/src/../include/mcl/bit/bit_count.hpp:44:37: error: expected ‘;’ before ‘{’ token
     44 | constexpr size_t lowest_set_bit(T x)
        |                                     ^
        |                                     ;
     45 | {
        | ~                                    
  In file included from /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/common/fp/op/FPMulAdd.cpp:13:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/info.h: In function ‘constexpr FPT Dynarmic::FP::FPValue()’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/info.h:127:58: error: missing template arguments before ‘(’ token
    127 |     constexpr int highest_bit = mcl::bit::highest_set_bit(value);
        |                                                          ^
  In file included from /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/common/fp/op/FPMulAdd.cpp:16:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/unpacked.h: In function ‘constexpr Dynarmic::FP::FPUnpacked Dynarmic::FP::ToNormalized(bool, int, u64)’:
  /home/denik/touchHLE/vendor/dynarmic/src/dynarmic/../dynarmic/common/fp/unpacked.h:48:54: error: missing template arguments before ‘(’ token
     48 |     const int highest_bit = mcl::bit::highest_set_bit(value);
        |                                                      ^
  make[2]: *** [src/dynarmic/CMakeFiles/dynarmic.dir/build.make:169: src/dynarmic/CMakeFiles/dynarmic.dir/common/fp/op/FPMulAdd.cpp.o] Ошибка 1
  make[1]: *** [CMakeFiles/Makefile2:1141: src/dynarmic/CMakeFiles/dynarmic.dir/all] Ошибка 2
  make: *** [Makefile:141: all] Ошибка 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /home/denik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.49/src/lib.rs:1104:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

in android build same

**Comment by ghost** [comment]
this problem in dynarmic? Or am I in trouble again?

**Comment by hikari-no-yume** [comment]
I'm not certain of this, but the problem might be that it's using a version of mcl installed on your system, rather than the one bundled with dynarmic, and it has an incompatible version? Can you check if you have it installed and, if so, try temporarily uninstalling it? I think there's a better fix but that would at least help diagnose if that's the issue.

**Comment by ghost** [comment]
> I'm not certain of this, but the problem might be that it's using a version of mcl installed on your system, rather than the one bundled with dynarmic, and it has an incompatible version? Can you check if you have it installed and, if so, try temporarily uninstalling it? I think there's a better fix but that would at least help diagnose if that's the issue.

how to check/delete it?

**Comment by hikari-no-yume** [comment]
Uhh, it would be with `apt`/`apt-get` I guess?

**Comment by ghost** [comment]
> Uhh, it would be with `apt`/`apt-get` I guess?

apt purge mcl?

**Comment by hikari-no-yume** [comment]
I've never used `purge` but `remove` should work? Be careful though, it could remove some package depending on it that you might want… if that's the case, you could look in `/usr/include` and see if there's a `mcl` directory somewhere and temporarily rename it.

**Comment by ghost** [comment]
> I've never used `purge` but `remove` should work? Be careful though, it could remove some package depending on it that you might want… if that's the case, you could look in `/usr/include` and see if there's a `mcl` directory somewhere and temporarily rename it.

I'll take a look now

**Comment by ghost** [comment]
I don't see the mcl folder

**Comment by hikari-no-yume** [comment]
Okay. I'm not sure what the issue is then. Maybe your C compiler is too old or too new? Sorry I can't be more help, it's not code I've written so it's very hard to say what is wrong.

**Comment by ghost** [comment]
my g++ and gcc version 9.4.0

**Comment by ghost** [comment]
btw in linux mint it builds normally

**Comment by ghost** [comment]
but in ubuntu 20.04 no

**Comment by hikari-no-yume** [comment]
Ah. dynarmic needs some pretty modern C++ features, so it might just be that Ubuntu 20.04 is too old.

**Comment by ghost** [comment]
> Ah. dynarmic needs some pretty modern C++ features, so it might just be that Ubuntu 20.04 is too old.

Ok, i updated to Ubuntu 22.04
