### ISSUE TITLE
Ubuntu 22.04 Build

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#126]
= note: LC_ALL="C" PATH="/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/denik/.cargo/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcTTdxVk/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcTTdxVk/symbols.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.0.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.1.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.10.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.11.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.12.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.13.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.14.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.15.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.2.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.3.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.4.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.5.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.6.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.7.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.8.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.touchHLE.d56bad10-cgu.9.rcgu.o" "/home/denik/touchHLE/target/release/deps/touchHLE.57zwv60rnb5iazyu.rcgu.o" "-Wl,--as-needed" "-L" "/home/denik/touchHLE/target/release/deps" "-L" "/home/denik/touchHLE/target/release/build/sdl2-sys-7bb98a404b6faffa/out/lib64" "-L" "/home/denik/touchHLE/target/release/build/sdl2-sys-7bb98a404b6faffa/out/lib" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dr_mp3_wrapper-3f77723e19ed1136/out" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out/lib" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out/lib64" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out/build/externals/fmt/" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out/build/externals/mcl/src/" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out/build/externals/zydis/" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_dynarmic_wrapper-d55aa5e3f3facd30/out" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_openal_soft_wrapper-1d84cf65992201b5/out/linux/lib" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_openal_soft_wrapper-1d84cf65992201b5/out/linux/lib64" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_pvrt_decompress_wrapper-922ec907b199688b/out" "-L" "/home/denik/touchHLE/target/release/build/touchHLE_stb_image_wrapper-157d6357738be838/out" "-L" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/denik/touchHLE/target/release/deps/libcaf-eadb6ce1b3847cd9.rlib" "/home/denik/touchHLE/target/release/deps/libhound-12148e60026bc4b9.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_gl_bindings-a4b700fba654b2ea.rlib" "/home/denik/touchHLE/target/release/deps/libsdl2-6775c2bd408f0142.rlib" "/home/denik/touchHLE/target/release/deps/libsdl2_sys-94496f841dbe0f32.rlib" "/home/denik/touchHLE/target/release/deps/libmach_object-47bae16461b978a4.rlib" "/home/denik/touchHLE/target/release/deps/liblibc-ddbc2122b1a790d2.rlib" "/home/denik/touchHLE/target/release/deps/libthiserror-f4bba75a8807532d.rlib" "/home/denik/touchHLE/target/release/deps/libuuid-6170b09b65120120.rlib" "/home/denik/touchHLE/target/release/deps/liblog-231e03fae6ce9fea.rlib" "/home/denik/touchHLE/target/release/deps/liblazy_static-340011eba8b2d628.rlib" "/home/denik/touchHLE/target/release/deps/libbitflags-ed1146e934fe3b36.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_stb_image_wrapper-c33493cc551358ec.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_pvrt_decompress_wrapper-a9249c38e4123e1e.rlib" "/home/denik/touchHLE/target/release/deps/libzip-a1ba949c4a190dd0.rlib" "/home/denik/touchHLE/target/release/deps/libflate2-2ac9b6b0425b5853.rlib" "/home/denik/touchHLE/target/release/deps/libminiz_oxide-1326c340cf0e0edc.rlib" "/home/denik/touchHLE/target/release/deps/libadler-1761e995e31baec6.rlib" "/home/denik/touchHLE/target/release/deps/libbyteorder-3e267623c1918fe3.rlib" "/home/denik/touchHLE/target/release/deps/libcrc32fast-a4f1f90881822f17.rlib" "/home/denik/touchHLE/target/release/deps/libcfg_if-a7d3f62713af2583.rlib" "/home/denik/touchHLE/target/release/deps/librusttype-ac78b5701fc9e982.rlib" "/home/denik/touchHLE/target/release/deps/libab_glyph_rasterizer-bf48de2217513c32.rlib" "/home/denik/touchHLE/target/release/deps/libowned_ttf_parser-5a5ee5efb39315ac.rlib" "/home/denik/touchHLE/target/release/deps/libttf_parser-61c75b76f43706ae.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_dynarmic_wrapper-0d3db207373e7fb6.rlib" "/home/denik/touchHLE/target/release/deps/libplist-3450080131e82b16.rlib" "/home/denik/touchHLE/target/release/deps/libtime-0bb2b78c29d56f1d.rlib" "/home/denik/touchHLE/target/release/deps/libitoa-34ca1795afc08b5c.rlib" "/home/denik/touchHLE/target/release/deps/libtime_core-b757e4c3971621d2.rlib" "/home/denik/touchHLE/target/release/deps/libline_wrap-a070bdcfb8140ebe.rlib" "/home/denik/touchHLE/target/release/deps/libsafemem-2b517d8b4581ab3f.rlib" "/home/denik/touchHLE/target/release/deps/libxml-5a10200ed432bee5.rlib" "/home/denik/touchHLE/target/release/deps/libbase64-0c1aaddd9ed30a46.rlib" "/home/denik/touchHLE/target/release/deps/libindexmap-d7dd6eb2cba05ff6.rlib" "/home/denik/touchHLE/target/release/deps/libhashbrown-41eac18e9c1eb628.rlib" "/home/denik/touchHLE/target/release/deps/libserde-3d1743a114faad0f.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_openal_soft_wrapper-6d5fd744cace0c23.rlib" "/home/denik/touchHLE/target/release/deps/libtouchHLE_dr_mp3_wrapper-8a3287f2294f15c8.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8389830094602f5a.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-41c1085b8c701d6f.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-f733fcc57ce38b99.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-6495ec9d4ce4f37d.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-1e3796360cca5b49.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-2e7f329b154436e1.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1e1f5b8a84008aa8.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-cbcb223c64b13cf3.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b40bc72e060a8196.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-1eb33ae9877d3c0f.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-0335d894dd05bed7.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-076a893ead7e7ab5.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-2e924dd85b2e9d95.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7975ffb5e62386c4.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-285425b7cea12024.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-38694d775e998991.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-914eb40be05d8663.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-27094fcca7e14863.rlib" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-919e055b306699ae.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lsndio" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/denik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/denik/touchHLE/target/release/deps/libtouchHLE.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lsndio: No such file or directory
          collect2: error: ld returned 1 exit status

what to do?

**Comment by ghost** [comment]
I try to reinstall build-essential

**Comment by ghost** [comment]
> I try to reinstall build-essential

this don't help

**Comment by CodeNinja-sys** [comment]
now Ubuntu 22.04 is also not supported?? I don't understand what the damn build is at all

**Comment by ghost** [comment]
ok i used cargo build --release --no-default-features

and get   = note: /usr/bin/ld: cannot find -lopenal: No such file or directory
          collect2: error: ld returned 1 exit status

**Comment by ghost** [comment]
I fixed it by command "sudo apt install libsdl2-dev"
