### ISSUE TITLE
Asphalt 4 not open says to run with rust_backtrace=1

### ISSUE THREAD

**Issue by AllwinAristo** [hikari-no-yume/touchHLE#131]
help me how to change the value please..
![IMG_20230623_073950](https://github.com/hikari-no-yume/touchHLE/assets/87270583/f46f712b-030c-4693-b3db-2d6cac5923a5)

**Comment by hikari-no-yume** [comment]
This specific issue was fixed three months ago (c1c746202b499f1b1c9c3b2acd04bf7de7968637) but the fix isn't in a new release yet. In any case the game you want to run probably won't work for other reasons.
