### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by stagbar** [hikari-no-yume/touchHLE#135]
I tried running SpongeBob_ Tickler_ 2.0.0.ipa on touchhle
But it seems to have made a slight mistake

**Comment by stagbar** [comment]
and the file

**Comment by stagbar** [comment]
[https://mtmdev.org/forum/index.php?attachments/spongebob-tickler-2-0-0-ipa.1711/](url)

**Comment by stagbar** [comment]
^
| the file

**Comment by hikari-no-yume** [comment]
> ⚠️ Do not link to pirated content. “Abandonware” is also pirated content.

> please don't open issues about apps that aren't in [the supported list](https://github.com/hikari-no-yume/touchHLE/blob/trunk/APP_SUPPORT.md), unless you've got it partially working

https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md
