### ISSUE TITLE
Frame limiting

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#143]
Fastlane seems to get significantly higher framerates than 60fps a lot of the time, especially on less demanding tracks and on the menu. This is quite wasteful with CPU time, energy, battery life etc, and I believe this isn't faithful to the original OS. Perhaps `presentRenderbuffer:` needs to enforce a 60fps cap somehow. It should ideally not rely on vsync, because the user might have a monitor with a higher refresh rate than 60Hz.

**Comment by hikari-no-yume** [comment]
The DOOM iOS menu could also benefit from frame limiting, as @ciciplusplus noticed.

**Comment by Calinou** [comment]
When it renders above 60 FPS, do visuals become smoother? If so, I wouldn't hardcode a 60 FPS cap and let the user choose instead. (A default cap to 60 FPS sounds reasonable still, to avoid timing issues in games that have FPS-dependent behavior.)

**Comment by hikari-no-yume** [comment]
It depends entirely on the game! Some are written in a way where running at a higher frame rate than normal increases smoothness without incorrectly affecting game speed, others aren't. So I'd provide a way to turn off the limiter.
