### ISSUE TITLE
Nevermind it was a Draft 

### ISSUE THREAD

**Issue by RetroDevPR** [hikari-no-yume/touchHLE#152]
Nevermind

**Comment by hikari-no-yume** [comment]
> I've been an avid user of the TouchHLE iPhone Emulator for Android for some time 

Pro tip: Do not begin your request with an obvious lie. Your attempt at flattery backfires.

Also, I notice you copy-pasted [more or less the same request](https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/933) for another emulator. Don't do that.

The issues you raise are, in general, addressed by the README, which you should have read _before_ opening an issue.

Also I get the feeling you wrote this with ChatGPT or something. Please don't.

**Comment by hikari-no-yume** [comment]
To expand on the ChatGPT thing: here is what I think happened.

You wanted to make a simple request like: "please support newer iOS versions". You could have written just that, in an issue. That's all it would need to say.

But instead, you have expanded this into many paragraphs, most of which are irrelevant to the main request and only make it _harder_ to understand what you want. They also just take a lot of time to read and respond to. It is a waste of my time, and of yours.

Please bear this in mind for future contributions.
