### ISSUE TITLE
Wolf3d 1.0 Crush

### ISSUE THREAD

**Issue by MrWolf-Modded** [hikari-no-yume/touchHLE#155]
I run Wolf 3D on TouchHLE 2.0
![image](https://github.com/hikari-no-yume/touchHLE/assets/141437315/7321e22e-6a5c-487e-b8ab-01cbea911b5c)
I Click Than TouchHLE Crush

**Comment by hikari-no-yume** [comment]
Most likely it is not actually the supported version. Sorry, there's not much I can do.

**Comment by MrWolf-Modded** [comment]
i didn't run source code i run ipa
