### ISSUE TITLE
SONIC 1 Crashes on Touchhle |:

### ISSUE THREAD

**Issue by AEDOODLEDASHMAKE** [hikari-no-yume/touchHLE#166]
Partially work For Sonic 1 on iOS touchhle

https://github.com/hikari-no-yume/touchHLE/assets/146776526/2883adea-c3a4-4f4a-950f-ce4caf1f2e2f

Support on pull Request

**Comment by AEDOODLEDASHMAKE** [comment]
ipa file for https://archive.org/download/iOSObscura/iPhoneOS%202/com.sega.sonic1/

**Comment by hikari-no-yume** [comment]
Do not link to pirate sites. This is your first warning.

**Comment by nighto** [comment]
@AEDOODLEDASHMAKE this initial screen is just a standard iOS loading image file. It appearing does not mean that the emulator is successfully running the game. Also notice that most games would not work at this moment; only supported games are, well, supported, so only open issues for games listed on [this list](https://github.com/hikari-no-yume/touchHLE/blob/trunk/APP_SUPPORT.md).
Also: a game being available on Internet Archive does not mean it is not pirated. Rule number one is: do not link to pirate content.

**Comment by MilesTailsFan2005** [comment]
i tried the 2008 version aka the genesis emulator version and it does indeed not work only one close to boot was the Sonic at the Olympic Winter Games
