### ISSUE TITLE
Settings addment to the Emulator

### ISSUE THREAD

**Issue by Thetouchedjoe** [hikari-no-yume/touchHLE#168]
Yeah, I'm recently try the touchHLE and yeah I'm so confused how do I make Scale Hack so I'm really really hope to be added a Settings app to the emulator to set Themes, Language, Time and yeah ofc * Scale Hack *

Maybe possible to play other OS games to be playable in the future by like refuse the app to run on a diffrent architecture (possibly make more bugs) ?

From : Me (the idea for TouchHLE)
To : (Every single contributor in this emulator)

**Comment by hikari-no-yume** [comment]
This is a duplicate issue, please check existing issues before creating a new one.

**Comment by Thetouchedjoe** [comment]
Ok lol :)

**Comment by Thetouchedjoe** [comment]
Btw, thank you @hikari-no-yume for already notice that I'm duplicate a issue lol
