### ISSUE TITLE
a GUI if you play a unsupported game

### ISSUE THREAD

**Issue by Thetouchedjoe** [hikari-no-yume/touchHLE#170]
Ok, so far I see sort of tests by other unsupported games like there's a YouTuber testing a Tom love Angela game but resulting a crash after the Outfit7 logo. And also other lucky results to test an unsupported game. I'm having a idea so like if you install a unsupported game, there's a "?" icon in the app while bouncing says "Unsupported Game", if you press the game, there's a GUI which is a tab says " ? (Unsupported Game, check the game list of touchHLE (Error Code : idk)) and a Button says OK, if you press the button, you're leave the app

From : Me (the idea of touchHLE)
To : (every contributor to touchHLE)

**Comment by hikari-no-yume** [comment]
Please slow down. You are making too many feature requests. We have limited time.

Anyway, we can't magically know which games work before someone tries them, so we can't label games as unsupported. Sorry.

**Comment by Thetouchedjoe** [comment]
ok ok, though lol
