### ISSUE TITLE
add support for gameloft .ipa games  + add guid for building for linux

### ISSUE THREAD

**Issue by dananothername** [hikari-no-yume/touchHLE#171]

**Comment by hikari-no-yume** [comment]
These are completely unrelated requests and should not be in the same issue.

> add support for gameloft .ipa games

I refer you to the following part of the contributing guide, which you apparently ignored when making this issue:

> Please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about apps that aren't in [the supported list](https://github.com/hikari-no-yume/touchHLE/blob/trunk/APP_SUPPORT.md)

---

> add guid for building for linux

There is already [a guide for building touchHLE](https://github.com/hikari-no-yume/touchHLE/blob/trunk/BUILDING.md).
