### ISSUE TITLE
add drift effects on racing games by using the vibration effect (well, doubtly will added to the Settings GUI)

### ISSUE THREAD

**Issue by Thetouchedjoe** [hikari-no-yume/touchHLE#177]
ok, im trying Fastlane : Street Racing on the touchHLE, the gameplay seemly normal but everybody that has a gaming phone maybe really need realistic effects like Drifting that you can feel by the Vibration. so by the way on the idea of Settings GUI (by someone) not just add scale hack, and anything also have a option to turn on/off DriftEffectX 0.1.0 option to play racing games feel Real, if you added it to usability enhancement label, ok but if it closed, im just doing my own opinion

From : Me (the idea and the complainer of touchHLE, WPR and also Pinball)
To : (every single contributor to the emulator)

**Comment by hikari-no-yume** [comment]
Sorry, because you keep making unhelpful issues like this, I am going to block you.
