### ISSUE TITLE
A request for uploading the android version to coolapk

### ISSUE THREAD

**Issue by GuihongWang** [hikari-no-yume/touchHLE#180]
can i get a permission to upload in the [coolapk](https://coolapk.com)?

**Comment by Jaffhj** [comment]
WHAT is CoolAPK

**Comment by GuihongWang** [comment]
> WHAT is CoolAPK

a platform where chinese dev can upload their app on there(&a technal forum like xda)
![Screenshot_20231022_054512.jpg](https://github.com/hikari-no-yume/touchHLE/assets/57795156/af8c5dc2-99f8-4a38-a63e-165211404805)

and there have some app has open source on the github ![Screenshot_20231022_054614.jpg](https://github.com/hikari-no-yume/touchHLE/assets/57795156/5cd5ac65-cffb-4ea0-9366-00914a106131)
[easter egg](https://github.com/hushenghao/AndroidEasterEggs)

**Comment by Jaffhj** [comment]
Ok

**Comment by hikari-no-yume** [comment]
I don't speak Chinese, and because I do not live in China, I am not able to access the CoolAPK website. So, I can't upload touchHLE there.

I don't think there is a need to put touchHLE there.

**Comment by hikari-no-yume** [comment]
But, I am wondering. Is the Great Firewall causing problems for downloading touchHLE? Would it be easier if it was on https://touchhle.org/ instead, for example?

**Comment by GuihongWang** [comment]
> Great Firewall causing problems
![image](https://github.com/hikari-no-yume/touchHLE/assets/57795156/ffdec742-dc19-4700-aec1-3069470b5eec)

10 min for load & most time waste on picture 

![image](https://github.com/hikari-no-yume/touchHLE/assets/57795156/9bb25a54-6ea0-4f18-89a9-ab90440bc1b6)

12 min complete the load without youtube video

>I am not able to access the CoolAPK website. So, I can't upload touchHLE there.

it's their problem.and they don't want get ddos from china abroad ,so they just block the traffic from china abroad(except the coolapk client)

 and i want to  get a **permission** to upload on the coolapk that like the [magisk app](https://github.com/topjohnwu/Magisk) on coolapk(sorry about the grammer)

![Screenshot_20231027_184652.jpg](https://github.com/hikari-no-yume/touchHLE/assets/57795156/0babef41-0af5-463b-8c8b-6496041bae06)

**Comment by hikari-no-yume** [comment]
Can you access GitHub easily or is that also a problem?

**Comment by GuihongWang** [comment]
> Can you access GitHub easily or is that also a problem?

faster than touchhle 


but my windows workstation ERR_CONNECTION_TIME_OUT alway 


load github smoothly on my macbook

**Comment by GuihongWang** [comment]
> > Great Firewall causing problems

btw a traceroute on my macbook(use the same network with windows)

Traceroute has started…

traceroute to touchhle.org (165.22.201.201), 64 hops max, 72 byte packets
 1  104.28.0.0 (104.28.0.0)  38.539 ms  34.427 ms  23.543 ms
 2  104.29.67.1 (104.29.67.1)  23.165 ms  29.884 ms  64.099 ms
 3  172.71.208.3 (172.71.208.3)  39.319 ms  28.973 ms  28.973 ms
 4  198.41.140.54 (198.41.140.54)  61.061 ms  60.966 ms  61.394 ms
 5  * 198.41.160.17 (198.41.160.17)  143.428 ms *
 6  198.41.160.137 (198.41.160.137)  223.432 ms  227.453 ms *
 7  198.41.140.74 (198.41.140.74)  441.375 ms  236.659 ms  234.469 ms
 8  198.41.140.200 (198.41.140.200)  262.060 ms  239.855 ms  241.808 ms
 9  195.66.226.25 (195.66.226.25)  234.671 ms  234.397 ms  300.777 ms
10  138.197.244.89 (138.197.244.89)  418.709 ms  504.470 ms  451.191 ms
11  138.197.250.81 (138.197.250.81)  404.933 ms  244.349 ms  244.555 ms
12  * * *
13  * * *
14  * * *
15  shin.noyu.me (165.22.201.201)  336.006 ms  235.885 ms  236.491 ms

**Comment by hikari-no-yume** [comment]
Hmm, how good is the download speed for https://touchhle.org/app-archive/? I could make the homepage be more like that page.

**Comment by GuihongWang** [comment]
> Hmm, how good is the download speed for https://touchhle.org/app-archive/? I could make the homepage be more like that page.

2.97 sec without cache 

download speed is 20~10kb/s(i have 100 mbps network)

and [this](https://github.com/hikari-no-yume/touchHLE/issues/180#issuecomment-1782686698)?

**Comment by hikari-no-yume** [comment]
Ah okay, so still too slow. :(

Hmm. I guess I can see two options:

- I could give you or someone else permission to upload to CoolAPK.
- I could upload myself to some Chinese file hosting service and link to it.

What do you think about the second option? Is there a good one you trust?

**Comment by GuihongWang** [comment]
> Ah okay, so still too slow. :(
> 
> Hmm. I guess I can see two options:
> 
> * I could give you or someone else permission to upload to CoolAPK.
> * I could upload myself to some Chinese file hosting service and link to it.
> 
> What do you think about the second option? Is there a good one you trust?

1. Glad you gave me permission to upload.
2. [gitee](https://gitee.com/)? a git platform that support by chinese goverment
(the feature may like github )

like github pages --> [gitee pages](https://help.gitee.com/services/gitee-pages/)

and ci build

and they look like make a mirror for [touchhle](https://gitee.com/mirrors_hikari-no-yume/touchHLE)

**Comment by hikari-no-yume** [comment]
Hmm, unfortunately the gitee mirror does not mirror the releases :(

**Comment by GuihongWang** [comment]
> Hmm, unfortunately the gitee mirror does not mirror the releases :(

yes  so have to upload it manually

may be you can make a gitee account to upload ? and let me to contact gitee support to see if they could remove the mirror.

**Comment by GuihongWang** [comment]
> - I could upload myself to some Chinese file hosting service and link to it.


 maybe i can host some file on my [static stroage](https://static.marisa.ml)
(base on onedrive business &cloudflare worker) so it is faster and 100% cdn


but website host on gitee page ㄟ(  )ㄏ 
and translate by myself
