### ISSUE TITLE
Why Never 64bit iOS?

### ISSUE THREAD

**Issue by sekkit** [hikari-no-yume/touchHLE#181]
Is there any reason to never have a 64bit iOS support?

**Comment by hikari-no-yume** [comment]
Hi, thanks for your question. There's three parts to it really:

* Realistic expectations. It is already very difficult to get early (iPhone OS 2) games working, and each new iOS version we support will only increase the difficulty; the OS and apps for it only get more complex with time. 64-bit support first appears in iOS 7, but it would be a miracle if touchHLE could support even iOS 6.
* Implementation simplicity. touchHLE's code assumes 32-bit throughout. Making it support both 32-bit and 64-bit would make many things more complicated.
* Lack of interest in that era of apps. The touchHLE project exists to preserve an older, less cynical era of mobile gaming. By the time you have 64-bit-only iOS games coming out, the mobile app space had fully decayed into its current freemium economy where good games are rare. Moreover, later titles are usually available on Android too, and there's plenty of good emulation solutions for Android titles.

I hope that gives you some insight!

**Comment by LunatiKK13** [comment]
Touchhle is a miracle in itself. As soon as the YouTuber Mr. Sujano spoke of this emulator I immediately became happy. I'm like wow, at some point I'll be able to play cod zombies again. That game was fun to play when I was in high school. I grew up on early iOS games so as an android user it's nice to have a way to play them again. I never thought I'd see iOS emulation on Android. That is amazing. Thank you for all your work.

**Comment by Adamillo** [comment]
Does that mean that support for iOS 10.3.4 is probably not gonna be implemented either, since this is the last versions that supported 32-bit?

**Comment by lylythechosenone** [comment]
As @hikari-no-yume said, even iOS 6 support would be a miracle. iOS 10 is never happening.

**Comment by CaioFerreiraCD** [comment]
Que pena, queria joga Monster Hunter Freedom Unite de IOS🥺 ( eu sei que existe o de PSP, mas não tem aquela opção da mira grudada no monstro)

**Comment by SplaatSites** [comment]
iOS 9 support would be a miracle too

**Comment by JPC16** [comment]
What a shame. I just hope someone will fork that emulator to add support for 64-bit iOS.

**Comment by hikari-no-yume** [comment]
There are much better pathways to running 64-bit iOS games than forking touchHLE.

**Comment by SplaatSites** [comment]
> What a shame. I just hope someone will fork that emulator to add support for 64-bit iOS.

It will probably happen sometime in the future
