### ISSUE TITLE
WolfRPG missing triangles on Android

### ISSUE THREAD

**Issue by ciciplusplus** [hikari-no-yume/touchHLE#183]
Tested on Redmi 9C NFC, Driver info: OpenGL ES-CM 1.1 / Imagination Technologies / PowerVR Rogue GE8320

Bug is not very reproducable
![Screenshot_20231029-011542](https://github.com/hikari-no-yume/touchHLE/assets/91161081/dc2a0d81-8da6-430d-b8f3-b4677f0ae07e)
![Screenshot_20231029-012528](https://github.com/hikari-no-yume/touchHLE/assets/91161081/b23eb6ea-aa4f-41a5-af1c-35017c1c7b18)
![Screenshot_20231029-011533](https://github.com/hikari-no-yume/touchHLE/assets/91161081/0d934144-c6d7-405f-a640-f0b3520981db)
![Screenshot_20231029-011527](https://github.com/hikari-no-yume/touchHLE/assets/91161081/787efd48-9dc3-4372-b885-e9fa58fc3287)

**Comment by hikari-no-yume** [comment]
Huh. Doesn't look like z-fighting, maybe it's an off-by-one error somewhere?

**Comment by bexsella** [comment]
This occurs on Apple hardware, below are screenshots taken from a 5th Gen iPod Touch, with iOS 9.2:

![IMG_0878](https://github.com/hikari-no-yume/touchHLE/assets/9209221/8bb87dd6-068b-4203-bcbf-d18b715c16e4)
![IMG_0879](https://github.com/hikari-no-yume/touchHLE/assets/9209221/a4523a3e-3e7b-406d-9797-a879dfbba027)
![IMG_0880](https://github.com/hikari-no-yume/touchHLE/assets/9209221/f95b2c83-78b8-46ec-b32e-d0af0190c3b7)
![IMG_0881](https://github.com/hikari-no-yume/touchHLE/assets/9209221/bf8d8291-8d1d-4680-bd14-0f8f5383120e)

**Comment by ciciplusplus** [comment]
Oh interesting! maybe we can close the issue then

**Comment by hikari-no-yume** [comment]
Finally an excuse to use my “the bug is coming from inside the app” 👻 tag :3
