### ISSUE TITLE
File manager crashes when moving files to the touchHLE location (document provider)

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#185]
At least two people have reported this:

- Redmi Note 9, Android 12
- Xiaomi Poco M3 Pro 5G, Android 13

It worked in my original testing on the Nexus 5X running Android 8, but… now when I try it again with the release version, I get this crash. So maybe it's just completely broken?

**Comment by nighto** [comment]
Also happens with me on Galaxy S9, Android 10. Had to use a different file manager (Samsung's "My Files") to be able to move apps to the right place.

**Comment by nighto** [comment]
Tip for users who faced this issue: the easiest way to copy files to touchHLE (tested on Galaxy S9, Android 10) was with AirDroid, with it I was able to copy from PC directly to touchhle_apps directory on the phone.

The screenshot below shows the right location to put apps (you probably need to open touchHLE at least once for this directory to be created):

![image](https://github.com/hikari-no-yume/touchHLE/assets/397851/1a0f498a-f628-48b2-82e4-87edcf1dcadb)

**Comment by hikari-no-yume** [comment]
I gave up on fixing it, Android is a hell OS: https://github.com/hikari-no-yume/touchHLE/commit/5b62b1f2abd272258e82841a60abe69c78db2dd8
