### ISSUE TITLE
Random app order on Android

### ISSUE THREAD

**Issue by nighto** [hikari-no-yume/touchHLE#187]
After copying a bunch of apps to touchhle_apps directory, on PC they look alphabetically sorted (except "Chefs" which full name is "Superstar Chefs", so technically that's still correct):

![image](https://github.com/hikari-no-yume/touchHLE/assets/397851/9b518470-bec4-40ab-8507-ca3fe2322594)
![image](https://github.com/hikari-no-yume/touchHLE/assets/397851/173a955e-59f1-4d43-8bfb-486cd6cd0206)
![image](https://github.com/hikari-no-yume/touchHLE/assets/397851/1b3addea-cd8d-489a-ad96-b0090b35e58e)

But after copying the same files to Android, the order is a bit random:

![Screenshot_20231101-141248_touchHLE](https://github.com/hikari-no-yume/touchHLE/assets/397851/c3f50d00-905a-46d7-a57b-775eed8b41fc)
![Screenshot_20231101-141252_touchHLE](https://github.com/hikari-no-yume/touchHLE/assets/397851/9fb85ffa-0e74-49ec-bd8f-866e8d7d0410)
![Screenshot_20231101-141255_touchHLE](https://github.com/hikari-no-yume/touchHLE/assets/397851/3b7633ab-5c77-4c8b-b485-95af08ca3635)

At first I thought it could be the order that the files were copied (as in, sorting by date last modified) but I first copied Doom2rpg, then KataDama, then all others. Doom2rpg is on the last place but KataDama is not the second to last.

**Comment by nighto** [comment]
Also because SMB is between two Donut Games games, it is not sorted by Bundle Identifier as well.

**Comment by ghost** [comment]
Renaming the files inside the apps folder also just shuffles them around randomly.

**Comment by Jaffhj** [comment]
Donut Games
List Of Games
1. lucky Coins
2. castle smasher
3. Monkey Flight
4. Sunday  Lawn
5. Jingle Crash
6. Camelot
7.  Rat on RUN
8. Traffic Rush
9. Ich Escort
10. Alice Greenfingers
11. Spiker
12. Cows in Space
13. Gold Miner nie
14. Titanic
15. Action Hero
16. Ruberth
17. Rat on a scooter XL
18. Comet Racer
19. Superstatuetką Chefs
20. Parachute
21. Action Buggy
22. Cat Physics
23. Urban Ninja
24. Rat on a skateboard

**Comment by ciciplusplus** [comment]
@hikari-no-yume could be closed now, right?

**Comment by hikari-no-yume** [comment]
Oh yeah, I'd forgotten about this issue. Thanks for the reminder.

This has been fixed in aaddb623a48f84faac61eedea288fa53a63d8d30.
