### ISSUE TITLE
Missing _pthread_cond_init for COD Zombies

### ISSUE THREAD

**Issue by TylerJaacks** [hikari-no-yume/touchHLE#191]
App bundle info:
- Display name: COD Zombies
- Version: 1.0.0
- Identifier: com.activision.callofduty
- Internal name (canonical): kiwi.app
- Minimum OS version: 2.2.1

`thread 'main' panicked at src\dyld.rs:535:9:
Call to unimplemented function _pthread_cond_init`

It looks like the app is looking _pthread_cond_init in "libstdc++.6.dylib"

**Comment by hikari-no-yume** [comment]
> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
