### ISSUE TITLE
Missing setStatusBarStyle is needed for Trism

### ISSUE THREAD

**Issue by TylerJaacks** [hikari-no-yume/touchHLE#192]
App bundle info:
- Display name: Trism
- Version: 1.2
- Identifier: com.demiforcegames.trism
- Internal name (canonical): Trism.app
- Minimum OS version: 2.1

`Object 0x3000b110 (class "UIApplication", 0x3000ae80) does not respond to selector "setStatusBarStyle:"!`

Definitions based on iOS Framework Headers: 

`-(void)setStatusBarStyle:(int)style animated:(BOOL)animated;`
`-(void)setStatusBarStyle:(int)style duration:(double)duration;`
`-(void)setStatusBarStyle:(int)style animation:(int)animation;`
`-(void)setStatusBarStyle:(int)style animation:(int)animation startTime:(double)time duration:(double)duration curve:(int)curve;`
`-(void)setStatusBarStyle:(int)style animationParameters:(id)parameters;`

**Comment by hikari-no-yume** [comment]
> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
