### ISSUE TITLE
Does not have simple setter method for window, use fallback for MGS Touch

### ISSUE THREAD

**Issue by TylerJaacks** [hikari-no-yume/touchHLE#193]
App bundle info:
- Display name: MGSTouch
- Version: 1.0.0
- Identifier: com.konami.mgst
- Internal name (canonical): METAL GEAR SOLID TOUCH.app
- Minimum OS version: 2.0

`not implemented: TODO: object 0x3007a000 does not have simple setter method for window, use fallback`

**Comment by hikari-no-yume** [comment]
> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
