### ISSUE TITLE
Cant run Angry birds on TouchHLE

### ISSUE THREAD

**Issue by GSH23** [hikari-no-yume/touchHLE#199]
I dont understand this:
touchHLE v0.2.1 — https://touchhle.org/

No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::app_picker: Warning: couldn't load icon for app bundle touchHLE_apps\ROBLOX 2.3.1 (Decrypted).ipa: Could not read icon file (displaying placeholder instead)
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.6.0 - Build 30.0.101.1273 / Intel / Intel(R) UHD Graphics 630
touchHLE::window: New controller connected: Xbox 360 Controller. Left stick = device tilt. Right stick = touch input (press the stick or shoulder button to tap/hold).
Picked: touchHLE_apps\Angry Birds Lite.ipa
App bundle info:
- Display name: Angry Birds
- Version: 1.3.0
- Identifier: com.clickgamer.AngryBirdsLite
- Internal name (canonical): AngryBirdsLite.app
- Minimum OS version: 3.0

Warning: app requires OS version 3.0. Only iPhone OS 2 apps are currently supported.
No options found for this app in touchHLE_default_options.txt
No options found for this app in touchHLE_options.txt

touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.6.0 - Build 30.0.101.1273 / Intel / Intel(R) UHD Graphics 630
touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
touchHLE::dyld: Warning: unhandled external relocation "_OBJC_EHTYPE_$_NSException" in "AngryBirdsLite" at 0x1a4cb8, 0x1a4ccc
touchHLE::dyld: Warning: unhandled non-lazy symbol "_exit" at 0x1a0050 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCFBundleNameKey" at 0x1a0054 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCFBundleVersionKey" at 0x1a0058 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSDefaultRunLoopMode" at 0x1a009c in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSFileModificationDate" at 0x1a0198 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSGregorianCalendar" at 0x1a019c in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCFTypeArrayCallBacks" at 0x1a01a0 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSHTTPCookieDomain" at 0x1a01a4 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSHTTPCookieValue" at 0x1a01a8 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_CGRectZero" at 0x1a01ac in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSHTTPCookieName" at 0x1a01b4 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSHTTPCookiePath" at 0x1a01b8 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSLocalizedDescriptionKey" at 0x1a01c4 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___objc_personality_v0" at 0x1a01c8 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kABPersonEmailProperty" at 0x1a01cc in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCLLocationAccuracyKilometer" at 0x1a01d0 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_CGRectNull" at 0x1a01d4 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIImagePickerControllerOriginalImage" at 0x1a01d8 in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIImagePickerControllerEditedImage" at 0x1a01dc in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_NSUnderlyingErrorKey" at 0x1a01ec in "AngryBirdsLite"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3800c8e0 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000ca90), 0xfffffe54, 0xfffffe54) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe54) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe54) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000bc20, 0x3000c000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000bc30, 0x3000c000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e38), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e20), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e08), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182df0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182dd8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182dc0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182da8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182d90), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e50), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e74), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182e8c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182ea4), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182ebc), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182ed4), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182eec), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x182f0c), 0x0, 0x1000) (unimplemented)
touchHLE::window: New controller connected: Xbox 360 Controller. Left stick = device tilt. Right stick = touch input (press the stick or shoulder button to tap/hold).
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your connected controller's left analog stick will be used for accelerometer simulation.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL 4.6.0 - Build 30.0.101.1273 / Intel / Intel(R) UHD Graphics 630
thread 'main' panicked at 'Call to unimplemented function _CCCrypt', src\dyld.rs:535:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Register state immediately after panic:
         R0: 0x00000001  R1: 0x00000000  R2: 0x00000001  R3: 0xfffff8d8
         R4: 0xfffffa70  R5: 0x00000000  R6: 0x0000127e  R7: 0xfffff914
         R8: 0x00001280  R9: 0xfffff8f8 R10: 0x00001280 R11: 0x00001270
        R12: 0x300bd570  SP: 0xfffff8b8  LR: 0x0014a274  PC: 0x00182f88
Attempting to produce stack trace for main thread:
 0. 0x182f88 (PC)
 1. 0x14a274 (LR)
 2. 0xce54
 3. 0x5c74
 4. 0x6dd8
 5. 0x7522c
 6. [host function]
 7. 0x3ac4
Next FP (0x0) is outside the stack.

how to fix this?

**Comment by hikari-no-yume** [comment]
READ THE TEXT BEFORE DELETING IT THANKS

**Comment by TouchHLEuser** [comment]
BRO💀
