### ISSUE TITLE
"UITextView" is unimplemented

### ISSUE THREAD

**Issue by creeper451** [hikari-no-yume/touchHLE#201]
I wanted to try playing Fruit Ninja on the emulator running on my laptop, but when I launch the app, I encounter an issue. I know you mentioned not to bring up non-working games, but I saw someone on YouTube successfully running the game.
https://www.youtube.com/watch?v=I-42TO9AVdM
here is the output from the emulator:
[output.txt](https://github.com/hikari-no-yume/touchHLE/files/13324925/output.txt)

**Comment by hikari-no-yume** [comment]
That person wasn't running it on an official release or a build from trunk. Sorry, I know it's not easy to tell.

**Comment by hikari-no-yume** [comment]
FYI I think that video is plagiarised from @ciciplusplus's Twitter 😞
