### ISSUE TITLE
multi-touch not working for cave bowling

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#203]
multi-touch not working for cave bowling 
 Without this, level 15 in this game is simply impossible

**Comment by ciciplusplus** [comment]
This is a no issue, this level/game doesn't require the multi-touch
<img width="592" alt="Screenshot 2023-11-19 at 01 19 59" src="https://github.com/hikari-no-yume/touchHLE/assets/91161081/ae0be523-ed70-4c16-bde8-8247d3cf80b9">
<img width="592" alt="Screenshot 2023-11-19 at 01 21 39" src="https://github.com/hikari-no-yume/touchHLE/assets/91161081/eee6e78c-1fa9-46d6-bc95-7a7522115855">
