### ISSUE TITLE
provide user agreement and privacy agreement？

### ISSUE THREAD

**Issue by GuihongWang** [hikari-no-yume/touchHLE#207]
i try to upload it on coolapk but stuck on provide user agreement and privacy agreement at the first time sartup screen or website 
![image.png](https://s2.loli.net/2023/11/24/E8CG6WSPrpvDLU3.png)

the example you can find on [tencent appbao](https://wikinew.open.qq.com/?title=%E9%9A%90%E7%A7%81%E6%9D%83%E9%99%90%E5%AE%A1%E6%A0%B8%E8%A7%84%E8%8C%83#/iwiki/875339652)

and [i18n](https://github.com/hikari-no-yume/touchHLE/issues/202)?

**Comment by hikari-no-yume** [comment]
There is no privacy policy because touchHLE does not collect any information from its users, and there is no user agreement beyond the license terms.

Unfortunately even if I did write policies for touchHLE, I definitely could not provide them in Chinese, so I don't think I can help. Sorry.
