### ISSUE TITLE
"error: could not find native static library `SDL2-static`" message

### ISSUE THREAD

**Issue by GamingDucking** [hikari-no-yume/touchHLE#208]
So i was compiling touchHLE on MSYS2, and i got this error message "error: could not find native static library `SDL2-static`, perhaps an -L flag is missing?"

Any ideas on fixing this?

**Comment by hikari-no-yume** [comment]
I've hit issues like this before where, for some reason, a library has a slightly different name on different platforms. But FYI, building SDL2 is handled by an external crate (Rust-SDL2), so it's probably not something you can fix in touchHLE's code directly.

**Comment by GamingDucking** [comment]
i decided to retry the building of the emulator and i cleaned the directory and tried again. this time it stopped at "error: could not find native static library `fmtd`, perhaps an -L flag is missing?".

**Comment by hikari-no-yume** [comment]
If you edit `src/cpu/dynarmic_wrapper/build.rs` and change `"fmtd"` to `"fmt"`, that might fix it.

**Comment by GamingDucking** [comment]
it fixed it, but now i have some problems with cmake since it gave this error to me: "error: failed to run custom build command for `touchHLE_openal_soft_wrapper v0.2.1 (D:\touchhle\src\audio\openal_soft_wrapper)`"

I am using msys2 for building the emulator.

**Comment by hikari-no-yume** [comment]
Can you please post the full error? A single-line summary isn't enough.

**Comment by hikari-no-yume** [comment]
But uh, I haven't tested MSYS2 as a build environment for touchHLE. I'm not sure I'd recommend it.

**Comment by GamingDucking** [comment]
> Can you please post the full error? A single-line summary isn't enough.

[error.txt](https://github.com/hikari-no-yume/touchHLE/files/13626773/error.txt)
Also, i dont exactly which build environment i was using right now (MSYS2), so i have no idea which one i can use.

**Comment by hikari-no-yume** [comment]
Wow, that error suggests a problem with MSYS2 itself, I can't help you there.

The only tested toolchain on Windows is Visual Studio.

**Comment by GamingDucking** [comment]
I see. I will figure it out how to bulid it on Visual Code whenever I have time.

**Comment by hikari-no-yume** [comment]
Visual Studio Code won't work, it's just a text editor. You need some version of Visual Studio with the C++ toolchain installed. Also, you don't actually interact with it in order to build touchHLE, it is just something that needs to have been installed.
