### ISSUE TITLE
Add emulator shortcut functionality 

### ISSUE THREAD

**Issue by upintheairsheep** [hikari-no-yume/touchHLE#21]
Please make a command to create a shortcut in the programs or applications folder in the OS that points to the app of your choice along with its icon, which requires the “install” or “point” command in the binary to be passed first.

**Comment by hikari-no-yume** [comment]
Every OS I'm aware of has some way to create shortcuts like this for arbitrary command-line apps, so there's no need for the emulator to provide this.

Also, I appreciate your enthusiasm, but please slow down with how often you're commenting before I am forced to force you to.
