### ISSUE TITLE
do not give a rating of 2 if the game only has a black screen without a crash

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#210]
it has only one error: 0x3000be80

**Comment by hikari-no-yume** [comment]
Sorry, can you give more context? I do not understand the issue.

**Comment by omagadsamsa** [comment]
> Sorry, can you give more context? I do not understand the issue.

touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.5.13399 Compatibility Profile Context 15.201.1151.1008 / ATI Technologies Inc. / AMD Mobility Radeon HD 5000 Series
touchHLE::mach_o: Loading armv6 slice for "Gridlock"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___objc_personality_v0" at 0xb008 in "Gridlock"
CPU emulation begins now.
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x3000b4e0 left unreplaced
or other errors:<html>
<body>

It doesn't crash but black screen stays. app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
and games that have bugs with others and are on the list of working stars with two stars:[iFart](https://appdb.touchhle.org/apps/93) [Strategic Assault](https://appdb.touchhle.org/apps/19)[Labyrinth](https://appdb.touchhle.org/apps/99)

**Comment by ciciplusplus** [comment]
This issue doesn't have much to do with touchHLE itself - appdb submissions are community driven.
