### ISSUE TITLE
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#211]
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.5.13399 Compatibility Profile Context 15.201.1151.1008 / ATI Technologies Inc. / AMD Mobility Radeon HD 5000 Series

**Comment by hikari-no-yume** [comment]
This is not an error, it says “trying” because the first attempt might fail. The second attempt succeeds.
