### ISSUE TITLE
Call of duty World at War Zombies not supported?

### ISSUE THREAD

**Issue by MuzakyGood** [hikari-no-yume/touchHLE#212]
I really want to play that game but the game only supports old IOS and I don't have an old iPhone, can you make the game support this IOS emulator?

**Comment by hikari-no-yume** [comment]
Sorry, we do not take requests, we all have limited time and work on what personally interests us. Also, please read the text in the new issue box before deleting it, that's what it's there for.

**Comment by MuzakyGood** [comment]
> Sorry, we do not take requests, we all have limited time and work on what personally interests us. Also, please read the text in the new issue box before deleting it, that's what it's there for.

I can only hope that you are enthusiastic about working on this emulator project so that many games are supported in this emulator.
