### ISSUE TITLE
when i add the streetracer.app, the start screen opens and then just stops. I have tried redoing it but it didnt work. But I have seen the videos and I can tell you put alot of work into it and with an emulaator thats running different software.. it wotn work all th etime. but good job making this

### ISSUE THREAD

**Issue by iplayfastandfurious** [hikari-no-yume/touchHLE#213]

**Comment by hikari-no-yume** [comment]
What OS are you using, what version of touchHLE, and what version of the game?

**Comment by iplayfastandfurious** [comment]
I'm using it on my hp laptop, touchHLE v0.2.1, and the game is v1.0 ipa

**Comment by hikari-no-yume** [comment]
[As you can see in the application compatibility database](https://appdb.touchhle.org/apps/6), Fastlane 1.0 isn't a known-working version, so that could be your problem. Good luck.
