### ISSUE TITLE
[Question] When will the IOS 3.0 emulator

### ISSUE THREAD

**Issue by MuzakyGood** [hikari-no-yume/touchHLE#215]
There are lots of good games on IOS 3.0, when do you think? Is that still just a plan?
`I read that in github Coming Soon IOS 3.0 emulator `

**Comment by nighto** [comment]
There is some early support, but at this moment most games will crash the emulator. Please check the https://appdb.touchhle.org for specific games that are supported.

**Comment by MuzakyGood** [comment]
> There is some early support, but at this moment most games will crash the emulator. Please check the https://appdb.touchhle.org for specific games that are supported.

Interesting, I hope many iOS 3.0 games support it :D

**Comment by hikari-no-yume** [comment]
The answer is that it's done when it's done.

**Comment by MuzakyGood** [comment]
> There is some early support, but at this moment most games will crash the emulator. Please check the https://appdb.touchhle.org for specific games that are supported.

What iOS 3.0 games are supported?

**Comment by hikari-no-yume** [comment]
We don't know.
