### ISSUE TITLE
Engine by Sunwoo games(Bestsungames)

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#217]
1.this is an engine that is used in all games from these developers, but there is one problem, this is Castle War, I recently (almost a week ago) found a version for iOS 3, when support for iOS 3 was added in the emulator, I launched this version (1.3.2) and everything worked until the moment of gameplay, it started, the sound worked longer than in other versions and it crashed after 5 seconds, perhaps it uses a modified engine and several patches are needed to solve these problems
2.the engine from the game Numba, the developers used two games for them, Numba runs fine but low grav racer only the menu worked, perhaps it also has a modified engine and requires several patches

**Comment by hikari-no-yume** [comment]
Please don't open issues requesting support for specific games.
