### ISSUE TITLE
after killing the boss it crashes on any episode in wolfenstein 3d 1.3

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#218]
This morning I was playing through the game on version 1.3 and noticed that after killing the boss and completing the level itself, the game crashes, of course you can go through the second episode of the first level again on version 1.1 and run this save on 1.3, but you still need to solve the problem if you want it

**Comment by omagadsamsa** [comment]
in version 1.2 the same thing happens

**Comment by sunflowers33d** [comment]
these notes can all go on https://appdb.touchhle.org/

**Comment by MuzakyGood** [comment]
> This morning I was playing through the game on version 1.3 and noticed that after killing the boss and completing the level itself, the game crashes, of course you can go through the second episode of the first level again on version 1.1 and run this save on 1.3, but you still need to solve the problem if you want it

I can't enter the game on touchHLE Android

**Comment by omagadsamsa** [comment]
> > This morning I was playing through the game on version 1.3 and noticed that after killing the boss and completing the level itself, the game crashes, of course you can go through the second episode of the first level again on version 1.1 and run this save on 1.3, but you still need to solve the problem if you want it
> 
> I can't enter wolfenstein 3D on touchHLE Android

in my new huawei(2018) no works ports for old android

**Comment by MuzakyGood** [comment]
> > > This morning I was playing through the game on version 1.3 and noticed that after killing the boss and completing the level itself, the game crashes, of course you can go through the second episode of the first level again on version 1.1 and run this save on 1.3, but you still need to solve the problem if you want it
> > 
> > I can't enter wolfenstein 3D on touchHLE Android
> 
> in my new huawei(2018) no works ports for old android

I use Samsung A03 it crashes when pressing the screen `Touch any screen` crashed immediately

**Comment by ciciplusplus** [comment]
@omagadsamsa please post the crash log.

As a reminder:

> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.

**Comment by omagadsamsa** [comment]
ouchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/Wolfenstein+3D+-+Classic+Platinum+1.2-corepda.ipa
App bundle info:
- Display name: wolf3d+
- Version: 1.2
- Identifier: com.idsoftware.wolf3d
- Internal name (canonical): wolf3d.app
- Minimum OS version: 2.0

Using options from touchHLE_default_options.txt for this app: --landscape-right
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
touchHLE::mach_o: Loading armv6 slice for "wolf3d"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
touchHLE::dyld: Write reloc 0x3e6b0 target=0x3000b360 offset=0
touchHLE::dyld: Write reloc 0x3e6a4 target=0x3000b380 offset=0
touchHLE::dyld: Write reloc 0x3e680 target=0x3000b3a0 offset=0
touchHLE::dyld: Write reloc 0x3e688 target=0x3000b3c0 offset=0
touchHLE::dyld: Write reloc 0x3e6c8 target=0x3000b3c0 offset=0
touchHLE::dyld: Write reloc 0x3e6ac target=0x3000b3e0 offset=0
touchHLE::dyld: Write reloc 0x3e6d0 target=0x3000b400 offset=0
touchHLE::dyld: Write reloc 0x3e6ec target=0x3000b400 offset=0
touchHLE::dyld: Write reloc 0x3e6cc target=0x3000b420 offset=0
touchHLE::dyld: Write reloc 0x3e6e8 target=0x3000b420 offset=0
touchHLE::dyld: Write reloc 0x3e6a8 target=0x3000b460 offset=0
touchHLE::dyld: Write reloc 0x3e9bc target=0x3000b320 offset=0
touchHLE::dyld: Write reloc 0x3e694 target=0x3000b480 offset=0
touchHLE::dyld: Write reloc 0x3e6c0 target=0x3000b480 offset=0
touchHLE::dyld: Write reloc 0x3e6e4 target=0x3000b480 offset=0
touchHLE::dyld: Write reloc 0x3e700 target=0x3000b480 offset=0
touchHLE::dyld: Write reloc 0x3e6a0 target=0x3000b4a0 offset=0
touchHLE::dyld: Write reloc 0x3e690 target=0x3000b4c0 offset=0
touchHLE::dyld: Write reloc 0x3e6dc target=0x3000b4c0 offset=0
touchHLE::dyld: Write reloc 0x3e6f8 target=0x3000b4c0 offset=0
touchHLE::dyld: Write reloc 0x3e6d8 target=0x3000b4e0 offset=0
touchHLE::dyld: Write reloc 0x3e6f4 target=0x3000b4e0 offset=0
touchHLE::dyld: Write reloc 0x3e6e0 target=0x3000b500 offset=0
touchHLE::dyld: Write reloc 0x3e6fc target=0x3000b500 offset=0
touchHLE::dyld: Write reloc 0x3e6b4 target=0x3000b520 offset=0
touchHLE::dyld: Write reloc 0x3e6c4 target=0x3000b580 offset=0
touchHLE::dyld: Write reloc 0x3e69c target=0x3000b5a0 offset=0
touchHLE::dyld: Write reloc 0x3e6bc target=0x3000b5a0 offset=0
touchHLE::dyld: Write reloc 0x3e6d4 target=0x3000b5a0 offset=0
touchHLE::dyld: Write reloc 0x3e6f0 target=0x3000b5a0 offset=0
touchHLE::dyld: Write reloc 0x3e6b8 target=0x3000b5c0 offset=0
touchHLE::dyld: Write reloc 0x3e68c target=0x3000b5e0 offset=0
touchHLE::dyld: Write reloc 0x3e698 target=0x3000b620 offset=0
touchHLE::dyld: Write reloc 0x3e73c target=0x3000b560 offset=0
touchHLE::dyld: Write reloc 0x3e774 target=0x3000b310 offset=0
touchHLE::dyld: Write reloc 0x3e9f4 target=0x3000b310 offset=0
touchHLE::dyld: Write reloc 0x3e9f8 target=0x3000b310 offset=0
touchHLE::dyld: Write reloc 0x3e778 target=0x3000b550 offset=0
touchHLE::dyld: Write reloc 0x3e400 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e410 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e420 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e430 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e440 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e450 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e460 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e470 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e740 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e77c target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e9c0 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e9fc target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e744 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e780 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3e9c4 target=0x0 offset=0
touchHLE::dyld: Write reloc 0x3ea00 target=0x0 offset=0
touchHLE::dyld: __Znwm_ptr linked? = 0x0
CPU emulation begins now.
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x3000b870 left unreplaced
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::opengles::gles_guest: Warning: glGetError() returned 0x501
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::errno: TODO: errno accessed on thread 0 (will always be 0)
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::frameworks::audio_toolbox::audio_services: TODO: vibration (AudioServicesPlaySystemSound)
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
touchHLE::libc::posix_io::stat: Warning: fstat() call, this function is mostly unimplemented
Panic at src/dyld.rs:677:9: Call to unimplemented function _opendir
Register state immediately after panic:
	 R0: 0xfffff948	 R1: 0x0002ef40	 R2: 0x00000000	 R3: 0x00000002
	 R4: 0x00000047	 R5: 0x001df400	 R6: 0xffffff40	 R7: 0xfffffde0
	 R8: 0x00000000	 R9: 0x00000000	R10: 0x00000000	R11: 0x00000000
	R12: 0x001df860	 SP: 0xfffff904	 LR: 0x0000a55c	 PC: 0x0002e3fc
Attempting to produce stack trace for main thread:
 0. 0x2e3fc (PC)
 1. 0xa55c (LR)
 2. 0x567c
 3. 0x2b20c
 4. [host function]
 5. 0x2758
Next FP (0x0) is outside the stack.

**Comment by ciciplusplus** [comment]
@omagadsamsa what version of touchHLE are you using? is it an official build?

**Comment by omagadsamsa** [comment]
> @omagadsamsa what version of touchHLE are you using? is it an official build?

Some person gave me the apk, so now I’ll go through the boss on the original 0.2.1

**Comment by ciciplusplus** [comment]
@omagadsamsa don't open issues about unofficial builds here

**Comment by hikari-no-yume** [comment]
Deleted a post and locking due to piracy mention. This is your only warning.
