### ISSUE TITLE
make microphone support

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#219]
I recently tested games and saw the game Ultimate VR for 3.0 which requires a microphone (as I understand from the title background), perhaps it does not use a microphone, but it may also be required in some games that require a microphone

**Comment by omagadsamsa** [comment]
since I also found a game where you need a microphone, list: Ultimate VR, Building Destroyer

**Comment by hikari-no-yume** [comment]
Why should we add support for this, when these games do not work anyway?
