### ISSUE TITLE
The text on Super Monkey Ball's options screen looks really gnarly

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#22]
Not sure what's up with this. Missing gamma encoding perhaps? Of course, it's not the same font (Helvetica versus Liberation Sans) or the same font rendering system, but it seems weird that there's such a stark difference on that screen.

**Comment by Calinou** [comment]
Do you have a screenshot with pixel-perfect sizing and lossless compression? I don't have a way to run the game locally, but might be able to tell if it's an issue with font hinting, kerning or LCD subpixel optimization :slightly_smiling_face:

**Comment by hikari-no-yume** [comment]
Yeah, I have an iPod touch which I can use to grab screenshots. I don't remember if the images are lossless but they're good enough. I'll take some.

**Comment by hikari-no-yume** [comment]
Here are some images. Bear in mind that iPhone OS/iOS doesn't do subpixel optimisation or hinting AFAIK. Also bear in mind that while I have tried to pick a similar-looking font and font size for English, I did not make any such efforts for the Japanese fonts, I just picked ones I knew worked and was happy with that.

# Settings screen (`LANG=en`)

## touchHLE
![screenshot](https://user-images.githubusercontent.com/579774/217895699-537ce2a9-d15e-436f-ab9f-5c653d8d4742.png)
## iPod touch 2nd gen
![screenshot](https://user-images.githubusercontent.com/579774/217895995-0642798e-6aa3-432b-b290-9b234e716f51.png)

# Settings screen (`LANG=ja`)

## touchHLE
![screenshot](https://user-images.githubusercontent.com/579774/217896405-c7b94450-9bc1-4358-8723-8582da3bc0b4.png)
## iPod touch 2nd gen
![screenshots](https://user-images.githubusercontent.com/579774/217896524-05e645d3-91b6-4af5-a03f-886edfb7b624.png)

**Comment by Calinou** [comment]
There doesn't appear to be subpixel optimization or hinting on both iOS and TouchHLE – there's no color fringing when zooming in, and thin vectors "bleed" over to surrounding pixels on both axes.

The subtle black outlines around text make me think this is an issue with [premultiplied alpha](https://microsoft.github.io/Win2D/WinUI3/html/PremultipliedAlpha.htm) not being used for font rendering when it should be.

**Comment by hikari-no-yume** [comment]
I just realised it might be missing gamma encoding (linear RGB to sRGB conversion), and sure enough, adding `.powf(0.45)` did this:

![screenshot (with the text looking good now)](https://user-images.githubusercontent.com/579774/217898568-27023df9-d315-40e6-80bb-e0fab7d92c93.png)

**Comment by hikari-no-yume** [comment]
Oh so that's why it's only the white text that gets messed up… the black text is actually affected too, but it's much more subtle due to the gamma curve.

**Comment by hikari-no-yume** [comment]
Fixed this now. It turned out to have further subtleties. Gamma encoding must not be applied to the alpha channel, otherwise the black text becomes too bold instead.
