### ISSUE TITLE
Android with 32 bit processor

### ISSUE THREAD

**Issue by Yoi003** [hikari-no-yume/touchHLE#220]
Please make a version for Android with 32bits processor

**Comment by hikari-no-yume** [comment]
It is not trivial to support 32-bit Android, it would require a lot of effort to rewrite the CPU emulation. I also think you might be disappointed by the performance. If you have a phone with a 32-bit CPU, it is unlikely to be fast.

**Comment by Raypuia** [comment]
I think the only solution for that would be doing a NCE engine (native code execution) for older devices.
Melange does exactly this (as long as the device OS can handle armv6/armv7-a binaries).
EKA2L1 ARM emulator has 32bit support too although can't confirm how it performs on 32bit arch

**Comment by Yoi003** [comment]
But armeabi-v7a not is supported? That architecture isn't so older , until cod mobile support it and it is a very heavy game , try bro trying you don't lose anything

**Comment by omagadsamsa** [comment]
> But armeabi-v7a not is supported? That architecture isn't so older , until cod mobile support it and it is a very heavy game , try bro trying you don't lose anything

you just compared the game and the emulator, soon they will stop producing 32-bit games and emulators altogether and it will be useless since 64-bit has been dying out for a long time

**Comment by omagadsamsa** [comment]
> > But armeabi-v7a not is supported? That architecture isn't so older , until cod mobile support it and it is a very heavy game , try bro trying you don't lose anything
> 
> you just compared the game and the emulator, soon they will stop producing 32-bit games and emulators altogether and it will be useless since 64-bit has been dying out for a long time

and there are emulators that emulate wine/windows that can run touchle (an example from a person from 4pda)
![b590cd71-47a3-4c20-83ce-1082aeee9f51](https://github.com/hikari-no-yume/touchHLE/assets/149837198/99a5cb99-c24d-4874-b8e8-0317409858c4)

**Comment by Raypuia** [comment]
> you just compared the game and the emulator, soon they will stop producing 32-bit games and emulators altogether and it will be useless since 64-bit has been dying out for a long time

Tbf, 32bit hasn't died out yet (which is weird).
A lot of Android/KaiOS devices in developing countries still uses it for budget reasons.

**Comment by hikari-no-yume** [comment]
> try bro trying you don't lose anything

Actually, I do lose something. As I wrote in the code of conduct:

> It's especially important to value and respect others' time and energy: don't demand or expect anything to happen on any particular timescale, or even for anyone to do anything at all. We're all volunteers here, doing things for the love of it, and if you force us to spend a lot of time on you without a good reason, it's going to slowly chip away at our passion and enthusiasm.

A lot of time and effort would be required to support 32-bit Android, and I'd rather do other things with my life.
