### ISSUE TITLE
Attach "raw" apks to GitHub release?

### ISSUE THREAD

**Issue by TobiX** [hikari-no-yume/touchHLE#221]
Hi,

I like to use https://github.com/ImranR98/Obtainium to keep Android apps up-to-date. It supports updating apps directly from GitHub releases, but only if the apk is directly attached to the release (There is an open issue to support zipped packages).

Could you attach the apk directly to the GitHub Release in the future? The difference in size shouldn't matter that much, since an apk is already a fancy zip file...

**Comment by hikari-no-yume** [comment]
Sorry, I understand it is inconvenient, but I don't really want to do anything that might encourage distributing the APK without the accompanying documentation.
