### ISSUE TITLE
when an application or game opens, it remains in the same place

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#223]
when an application or game opens, it remains in the same place
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/60e138e2-8af7-4a6b-96b2-8d81a994b9de)

**Comment by hikari-no-yume** [comment]
Could you please elaborate on what the problem is?

**Comment by omagadsamsa** [comment]
> Could you please elaborate on what the problem is?

The translator is bad, when I launch the touchscreen it either shows a black screen without errors, or when I launch some game, a black screen is possible but there is sound

**Comment by hikari-no-yume** [comment]
The version number in the screenshot is v0.2.1-115-gb28184f. b28184f is not an official build of touchHLE so I can't provide support.

**Comment by omagadsamsa** [comment]
delete this issue in github
