### ISSUE TITLE
sf2 collection 

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#224]
street fighter 2 collection is launching for 1 second and then crashing if you could please make the game playable because I had a ipod touch 3 with game it was my favourite game even though it was a retro collection I really like 
the controls and the versions in particular so if you could make the game work that would be incredible

**Comment by hikari-no-yume** [comment]
As the text you are shown when creating a new issue states, please don't open issues for broken games.

**Comment by ghost** [comment]
sorry for the inconvenience

**Comment by hikari-no-yume** [comment]
It's okay. I hope that this game will be playable someday, but I have limited time unfortunately, so I only work on what I personally am interested in.

**Comment by ghost** [comment]
I hope you mange to one day make this project apple to play thousands of games someday
