### ISSUE TITLE
White screen on Retroid Pocket 2+

### ISSUE THREAD

**Issue by BomberDuck** [hikari-no-yume/touchHLE#225]
So I've been trying to play Touch and Roll on my Retroid Pocket 2+, and since the analog controls on DS don't reach the deadzone ingame, I tried using touchhle. The app works, but the only thing it shows is a white screen. Any help?

**Comment by hikari-no-yume** [comment]
According to Wikipedia, the Retroid Pocket 2+ has the Unisoc Tiger T310 as its SoC, and it seems this SoC has a PowerVR GPU. Unfortunately this white screen issue is a known problem for touchHLE on PowerVR devices. I don't know what causes it. I would like to fix it but it's not easy for me to do so as I don't have a phone with a PowerVR GPU.

**Comment by hikari-no-yume** [comment]
Closing since https://github.com/hikari-no-yume/touchHLE/issues/200 already tracks this.
