### ISSUE TITLE
"This software is made with love by a queer trans person" or equivalent

### ISSUE THREAD

**Issue by SoniEx2** [hikari-no-yume/touchHLE#227]
You should add something like this to the software! It makes it automatically more awesome!

(Obviously, please adjust it to your needs. "queer trans person" applies to us (sometimes) so that's why we put that in our own software.)

**Comment by hikari-no-yume** [comment]
90bbc943f9737702e493d35180163afb898cc6a7

**Comment by hikari-no-yume** [comment]
FWIW I do like the idea in principle but I don't tend to emphasise any marker of my identity in things I write other than my own username, and this project in particular is not a single-person project.

**Comment by hikari-no-yume** [comment]
Locked pre-emptively just in case someone adds an unpleasant comment.
