### ISSUE TITLE
support .ipg format

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#229]
I recently saw this format when I was looking for games to test, I know only one game on this format: bomberman touch

**Comment by parkerlreed** [comment]
From what I can tell ipg means it's an iPod click wheel game. Nothing for iOS should be in that format.

**Comment by hikari-no-yume** [comment]
Yes, touchHLE will not support iPod Classic games, the iPod did not run iPhone OS or anything even remotely similar to it.
