### ISSUE TITLE
when i open the game is crash

### ISSUE THREAD

**Issue by Migueli000** [hikari-no-yume/touchHLE#235]

**Comment by spetterman66** [comment]
What game? Please be descriptive.

________________________________
From: Migueli000 ***@***.***>
Sent: Saturday, January 20, 2024 5:58 PM
To: hikari-no-yume/touchHLE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hikari-no-yume/touchHLE] when i open the game is crash (Issue #235)
