### ISSUE TITLE
Interactive Buddy 2 (com.shockvaluegames.ibNextFinal)

### ISSUE THREAD

**Issue by Majesticgrey** [hikari-no-yume/touchHLE#236]
Ive tried using this game with it. I see it open to the sandbox area for like, a few milliseconds, and then it crashes.
Version: V.0.2.1
The game needs to be in landscape, with a slightly larger resolution. If you need more details, please tell me.
Game also appears as Int. Buddy 2 in the app explorer with a ? as the icon.  

Video:
https://www.youtube.com/watch?v=FcQM2yzzFDQ
Sorry if this isnt worded very well :(

**Comment by hikari-no-yume** [comment]
This is not a known-working game, please read the guidelines before creating an issue.

**Comment by Majesticgrey** [comment]
Oh ok. Well, ill go try to dig up my old iphone and hope that works. Do you want me to delete this?

**Comment by hikari-no-yume** [comment]
I already closed the issue so I don't need you to do anything. Good luck.
