### ISSUE TITLE
The Android version crashes whenever I press the Home or Recents button

### ISSUE THREAD

**Issue by xn117khdsh** [hikari-no-yume/touchHLE#237]
TouchHLE works perfectly on Android, but there is one major problem: Everytime I press the Home or Recent button on the phone, it crashes. I don't know why it happens. Can you fix the issue?

**Comment by hikari-no-yume** [comment]
This is a known issue and there is not an easy fix: https://github.com/hikari-no-yume/touchHLE/issues/147.
