### ISSUE TITLE
The app crashes immediately once it tries to load on android

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [hikari-no-yume/touchHLE#238]
the title explains it, the app has no icon, no specified version and when i try to open it it crashes, after a bit android thinks the app is broken, i will try the 0.20 version instead and see if that will work

**Comment by Jerty56** [comment]
> the title explains it, the app has no icon, no specified version and when i try to open it it crashes, after a bit android thinks the app is broken, i will try the 0.2.0 version instead and see if that will work

**Comment by GuythatUhmCreatesRandomStuff** [comment]
on My integrated powerVR tablet it works, but not on my MaliG52 gpu phone. (samsung)

**Comment by GuythatUhmCreatesRandomStuff** [comment]
Tablet: Android 10 / Phone: Android 12

**Comment by hikari-no-yume** [comment]
Please tell me:

- Exactly which version of touchHLE you are using
- Exactly what phone you are using (model number)

Also, please provide a copy of the log file. If you go to the “Files” app and can find touchHLE in it, there should be a log file.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
Latest version (and the second latest version tested) from the github, not from external source.

Log:
[log.txt](https://github.com/hikari-no-yume/touchHLE/files/14040250/log.txt)

Phone(European Samsung):
SM-A217F/DSN (Galaxy A21s)

if you want more details i can give more.

**Comment by hikari-no-yume** [comment]
Hmm, log looks normal but doesn't include the crash reason (probably my fault). If you can use logcat with the device connected over USB to a computer, you might be able to get the crash reason… but I appreciate that this might be quite complicated.

**Comment by damiennnnn** [comment]
Bit late here in the UK but I was tinkering around with touchHLE on my S23 Ultra

Similar issue, loading known working IPAs leads to a near instant crash to homescreen, i'll grab more info in the morning

edit: maybe not entirely relevant to the OP's issue

**Comment by HaZe5657** [comment]
Ahhh man.. I thought the app having no icon was normal. And I have the exact same issue, I'm running the same renderer as well, a Mali-G52 on a Motorola E40, Unisoc T700, Android 11. "None" of the games launch, not even super monkey Ball. I'll add an attachment showing the issue.

https://github.com/touchHLE/touchHLE/assets/85792795/feddfcc3-4fb1-4320-be75-c6408dd5b8f1

**Comment by HaZe5657** [comment]
Log, just in case if you've made reparations to logging from the time of this issue.
[log.txt](https://github.com/touchHLE/touchHLE/files/15070783/log.txt)

**Comment by hikari-no-yume** [comment]
@HaZe5657 Most of the games you have tried are not known to be working in touchHLE (check https://appdb.touchhle.org), so them crashing is expected. I am curious what's up with Fastlane and Super Monkey Ball though. Can you provide logs for those?

**Comment by hikari-no-yume** [comment]
Also, to be clear, the app having no icon _is_ normal. We still have not added an icon to any of the released versions.

**Comment by HaZe5657** [comment]
> @HaZe5657 Most of the games you have tried are not known to be working in touchHLE (check https://appdb.touchhle.org), so them crashing is expected. I am curious what's up with Fastlane and Super Monkey Ball though. Can you provide logs for those?

Oh. Well, it's the fact that every single one of them does not work. And for monkey ball and fastlane, how do I provide logs for those?

**Comment by hikari-no-yume** [comment]
The same way you provided the log for Red Alert.

**Comment by hikari-no-yume** [comment]
(Sorry, I got the app name wrong when I initially commented, fixed)

**Comment by HaZe5657** [comment]
@hikari-no-yume Log file for Fastlane, and as for monkey ball, (forgive me, I only tried it now, I just assumed this was something big, and that nothing would work.) it did work. However I was unable to control the game, presumably because my phone lacks a gyroscope.
[log.txt](https://github.com/touchHLE/touchHLE/files/15078861/log.txt)

**Comment by hikari-no-yume** [comment]
@HaZe5657 The tilt controls not working is because your phone is affected by https://github.com/touchHLE/touchHLE/issues/151. Sorry, it's a known issue.

As for Fastlane I'm not sure what's wrong. If you can try another version of it you might have more success, though I think the version you used is supposed to work from what I remember…

**Comment by HaZe5657** [comment]
@hikari-no-yume Yeah, is it because the fingerprint gets detected as a control device? I've had that issue come up lots, especially with old games.
I'll try another version then. Honestly, I think I'll just get an iphone 5 to quench my nostalgia.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
The issue is fixed by, itself? Anyways...
