### ISSUE TITLE
The macOS  x86_64 0.2.1 release instantly crashes with "Illegal instruction: 4" in the Terminal

### ISSUE THREAD

**Issue by ProstoTemich** [hikari-no-yume/touchHLE#239]
Device: MacBookPro2,1
macOS version: 10.7.5 (11G63)

**Comment by hikari-no-yume** [comment]
OS X Lion is a very old version of macOS, so I am not surprised that touchHLE wouldn't work with it. Sorry, it is probably not realistic for us to support versions of macOS that old.
