### ISSUE TITLE
failed to run build for windows with windows

### ISSUE THREAD

**Issue by omagadsamsa** [hikari-no-yume/touchHLE#241]
error: failed to run custom build command for `sdl2-sys v0.35.2 (https://github.com/hikari-no-yume/rust-sdl2.git?tag=touchHLE-2#15c58be7)`

Caused by:
  process didn't exit successfully: `c:\Users\bata2\AppData\Local\Temp\Rar$DRa8228.9317\touchHLE-tmp-mahjong\target\debug\build\sdl2-sys-ba174ff8681ed380\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\bata2\\.cargo\\git\\checkouts\\rust-sdl2-d99d7f693515dc24\\15c58be\\sdl2-sys\\SDL" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DSDL_SHARED=OFF" "-DSDL_STATIC=ON" "-DSDL_MAIN_HANDLED=ON" "-DCMAKE_INSTALL_PREFIX=c:\\Users\\bata2\\AppData\\Local\\Temp\\Rar$DRa8228.9317\\touchHLE-tmp-mahjong\\target\\debug\\build\\sdl2-sys-dcd356f6b56d89bd\\out" "-DCMAKE_C_FLAGS= -D__FLTUSED__ -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -D__FLTUSED__ -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=release"

  --- stderr
  thread 'main' panicked at C:\Users\bata2\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.49\src\lib.rs:1104:5:

  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: Cargo invocation failed.
        at t.Cargo.getCargoArtifacts (c:\Users\bata2\.vscode-insiders\extensions\vadimcn.vscode-lldb-1.10.0\extension.js:1:14943)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Object.open (c:\Users\bata2\.vscode-insiders\extensions\vadimcn.vscode-lldb-1.10.0\extension.js:1:13253)
Caused by: Error: exit code: 101.
        at ChildProcess.<anonymous> (c:\Users\bata2\.vscode-insiders\extensions\vadimcn.vscode-lldb-1.10.0\extension.js:1:16610)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at Process.onexit (node:internal/child_process:302:5)

**Comment by spetterman66** [comment]
Use the prebuilt binary: https://archive.org/download/ipod-2g-emulator/Ipod_2g_emulator.rar

**Comment by hikari-no-yume** [comment]
>  failed to execute command: program not found
>  is `cmake` not installed?

You need to install CMake. Sorry, I guess I forgot to add this to the building instructions.

**Comment by omagadsamsa** [comment]
> > failed to execute command: program not found
> > is `cmake` not installed?
> 
> You need to install CMake. Sorry, I guess I forgot to add this to the building instructions.

new problem:[Running] cd "c:\Users\bata2\Downloads\touchHLE-spore-wip\" && rustc build.rs && "c:\Users\bata2\Downloads\touchHLE-spore-wip\"build
error: environment variable `CARGO_MANIFEST_DIR` not defined at compile time
  --> build.rs:17:34
   |
17 |     let package_root = Path::new(env!("CARGO_MANIFEST_DIR"));
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: Cargo sets build script variables at run time. Use `std::env::var("CARGO_MANIFEST_DIR")` instead
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `cargo_license`
 --> build.rs:6:5
  |
6 | use cargo_license::{get_dependencies_from_cargo_lock, GetDependenciesOpt};
  |     ^^^^^^^^^^^^^ maybe a missing crate `cargo_license`?
  |
  = help: consider adding `extern crate cargo_license` to use the `cargo_license` crate

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.

[Done] exited with code=1 in 0.486 seconds

**Comment by hikari-no-yume** [comment]
Why are you running `rustc build.rs`?! Have you read the [building guide](https://github.com/hikari-no-yume/touchHLE/blob/trunk/dev-docs/building.md)?

**Comment by hikari-no-yume** [comment]
Also, please use triple-backticks when pasting logs like this, they are not pleasant to read otherwise.

**Comment by omagadsamsa** [comment]
> Почему ты бежишь `rustc build.rs`?! Вы читали [руководство по строительству](https://github.com/hikari-no-yume/touchHLE/blob/trunk/dev-docs/building.md) ?

My translator is stuck, I can’t properly read what to run, and I’m trying with all my might to launch

**Comment by hikari-no-yume** [comment]
Why do you want to build touchHLE yourself?

**Comment by omagadsamsa** [comment]
> Почему вы хотите создать TouchHLE самостоятельно?

a question that I’m embarrassed to answer because I have a lot of ideas

**Comment by hikari-no-yume** [comment]
I don't want to discourage you, but I think it is going to be very difficult to contribute, if you have to rely on machine translation. All the documentation and comments in this codebase are in American English, and it is very complicated technical English.

**Comment by omagadsamsa** [comment]
> Я не хочу вас разочаровывать, но думаю, что внести свой вклад будет очень сложно, если вам придется полагаться на машинный перевод. Вся документация и комментарии в этой базе кода написаны на американском английском, а это очень сложный технический английский.

yes, if I understood English, I could now do it, but now I can’t do it because I need to at least see how to run the finished code in visual studio code

**Comment by hikari-no-yume** [comment]
I don't know if Visual Studio Code works. You should use a command prompt and run `cargo run`.

**Comment by hikari-no-yume** [comment]
But you also need:

* Visual Studio with C++ tools (**not** Visual Studio Code)
* the git submodules
* Boost

https://github.com/hikari-no-yume/touchHLE/blob/trunk/dev-docs/building.md#general

**Comment by omagadsamsa** [comment]
> Я не знаю, работает ли код Visual Studio. Вам следует использовать командную строку и запустить `cargo run`.

(((C:\Users\bata2>cargo run
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` .
Colliding filename is: C:\Users\bata2\target\debug\deps\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` .
Colliding filename is: C:\Users\bata2\target\debug\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
error: failed to determine package fingerprint for build script for touchHLE v0.2.0 (C:\Users\bata2)
An I/O error happened. Please make sure you can access the file.

By default, if your project contains a build script, cargo scans all files in
it to determine whether a rebuild is needed. If you don't expect to access the
file, specify `rerun-if-changed` in your build script.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed for more information.

Caused by:
  failed to determine the most recently modified file in C:\Users\bata2

Caused by:
  failed to determine list of files in C:\Users\bata2

Caused by:
  Access denied. (os error 5)

Caused by:
  Access denied. (os error 5))))

**Comment by ciciplusplus** [comment]
You should run your command line as Admin

**Comment by omagadsamsa** [comment]
> You should run your command line as Admin

`C:\Windows\system32>cargo run
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Windows\system32)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Windows\system32)` .
Colliding filename is: C:\Windows\system32\target\debug\deps\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Windows\system32)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Windows\system32)` .
Colliding filename is: C:\Windows\system32\target\debug\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
error: failed to determine package fingerprint for build script for touchHLE v0.2.0 (C:\Windows\system32)
An I/O error happened. Please make sure you can access the file.

By default, if your project contains a build script, cargo scans all files in
it to determine whether a rebuild is needed. If you don't expect to access the
file, specify `rerun-if-changed` in your build script.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed for more information.

Caused by:
  failed to determine the most recently modified file in C:\Windows\system32

Caused by:
  failed to determine list of files in C:\Windows\system32

Caused by:
  Access denied. (os error 5)

Caused by:
  Access denied. (os error 5)  `

**Comment by ciciplusplus** [comment]
> C:\Windows\system32

WTF why you building inside your system folder?
you should build it inside the project checkout

**Comment by omagadsamsa** [comment]
> WTF why you building inside your system folder?
> you should build it inside the project checkout

C:\Windows\system32>cd c:\users\bata2

c:\Users\bata2>cargo run
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` .
Colliding filename is: c:\Users\bata2\target\debug\deps\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.2.0 (C:\Users\bata2)` .
Colliding filename is: c:\Users\bata2\target\debug\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
error: failed to determine package fingerprint for build script for touchHLE v0.2.0 (C:\Users\bata2)
An I/O error happened. Please make sure you can access the file.

By default, if your project contains a build script, cargo scans all files in
it to determine whether a rebuild is needed. If you don't expect to access the
file, specify `rerun-if-changed` in your build script.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed for more information.

Caused by:
   failed to determine the most recently modified file in c:\Users\bata2

Caused by:
   failed to determine list of files in c:\Users\bata2

Caused by:
   Access denied. (os error 5)

Caused by:
   Access denied. (os error 5)

**Comment by omagadsamsa** [comment]
I don’t know if it will start, but I was able to start the compiling process right now
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/90b9c020-1335-4fb4-af8f-d445223cd53e)

**Comment by omagadsamsa** [comment]
nooooo`error: failed to run custom build command for `touchHLE_stb_image_wrapper v0.2.0 (C:\Users\bata2\Downloads\touchHLE-spore-wip\src\image\stb_image_wrapper)`

Caused by:
  process didn't exit successfully: `C:\Users\bata2\Downloads\touchHLE-spore-wip\target\debug\build\touchHLE_stb_image_wrapper-8ef57df907447899\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\target\\debug\\build\\touchHLE_stb_image_wrapper-47b6251f17234262\\out\\206a00339ffa6e77-lib.o" "-c" "C:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\src\\image\\stb_image_wrapper\\lib.c"
  lib.c
  C:\Users\bata2\Downloads\touchHLE-spore-wip\src\image\stb_image_wrapper\lib.c(9): fatal error C1083: Cannot open include file: '../../../vendor/stb/stb_image.h': No such file or directory
  exit code: 2

  --- stderr


  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\target\\debug\\build\\touchHLE_stb_image_wrapper-47b6251f17234262\\out\\206a00339ffa6e77-lib.o" "-c" "C:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\src\\image\\stb_image_wrapper\\lib.c" with args "cl.exe" did not execute successfully (status code exit code: 2).


warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `touchHLE_dr_mp3_wrapper v0.2.0 (C:\Users\bata2\Downloads\touchHLE-spore-wip\src\audio\dr_mp3_wrapper)`

Caused by:
  process didn't exit successfully: `C:\Users\bata2\Downloads\touchHLE-spore-wip\target\debug\build\touchHLE_dr_mp3_wrapper-9cbf4d68941202a8\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\target\\debug\\build\\touchHLE_dr_mp3_wrapper-b424e80a82edf010\\out\\a204300accd97f17-lib.o" "-c" "C:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\src\\audio\\dr_mp3_wrapper\\lib.c"
  lib.c
  C:\Users\bata2\Downloads\touchHLE-spore-wip\src\audio\dr_mp3_wrapper\lib.c(8): fatal error C1083: Cannot open include file: '../../../vendor/dr_libs/dr_mp3.h': No such file or directory
  exit code: 2

  --- stderr


  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\target\\debug\\build\\touchHLE_dr_mp3_wrapper-b424e80a82edf010\\out\\a204300accd97f17-lib.o" "-c" "C:\\Users\\bata2\\Downloads\\touchHLE-spore-wip\\src\\audio\\dr_mp3_wrapper\\lib.c" with args "cl.exe" did not execute successfully (status code exit code: 2).`

**Comment by omagadsamsa** [comment]
hikari, I SAW an error where cmake is needed, I quickly set up everything there and clicked on open project and on visual studio, it demanded that in the touchle folder in x64 in debug in ALL_BUILD it demanded files there, I dragged all the files with this inscription there and now error 
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/97f40c4f-4a76-4625-a740-e9c39933db1d)
it denies me access to this folder

**Comment by omagadsamsa** [comment]
> hikari, I SAW an error where cmake is needed, I quickly set up everything there and clicked on open project and on visual studio, it demanded that in the touchle folder in x64 in debug in ALL_BUILD it demanded files there, I dragged all the files with this inscription there and now error ![image](https://private-user-images.githubusercontent.com/149837198/301266637-97f40c4f-4a76-4625-a740-e9c39933db1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjU3NzgsIm5iZiI6MTcwNjcyNTQ3OCwicGF0aCI6Ii8xNDk4MzcxOTgvMzAxMjY2NjM3LTk3ZjQwYzRmLTRhNzYtNDYyNS1hNzQwLWU5YzM5OTMzZGIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxODI0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTNiYjRiNzVmZjA2YWY1YWEwYjc4NjNlZmRjZGEzZWM4Yjc4OGFmOWViMDg3YjQ1OGRlYWNhMWVkNjgzZGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sAUlfPNLnCQ329oTvBRkBUr09kImyo9g4hdQduQ-Y_k) it denies me access to this folder

configure:
![image](https://github.com/hikari-no-yume/touchHLE/assets/149837198/b35be7a0-925a-4c28-96d9-72d99e5fae29)

**Comment by ciciplusplus** [comment]
Hello @omagadsamsa ,

As already was pointed out by @hikari-no-yume, please follow the [building docs](https://github.com/hikari-no-yume/touchHLE/blob/trunk/dev-docs/building.md)

If you believe there is the issue with build instructions, please open another issue.

Otherwise, we cannot debug your configuration issues and build problems for you, sorry.
