### ISSUE TITLE
Sourcing Dylibs

### ISSUE THREAD

**Issue by Vipitis** [hikari-no-yume/touchHLE#242]
I read the guides and docs and couldn't find a good answer. 

There is only limited dylibs included in this repository. In some forks there seem to be additional. 

Where could you source additional dylibs? I am not an Apple developer nor do I have Xcode. Is there other channels I am missing?

Or do additional libraries have to be reimplemented to comply with licenses?

**Comment by hikari-no-yume** [comment]
Most of the dylibs bundled with iPhone OS aren't GPL-licensed, which prevents us from simply taking Apple's versions; that would be copyright infringement. This is the reason only libgcc and libstdc++ are included. The dylibs you see in forks are not something I am willing to merge into the main project for this reason.

I can't tell you about the process, sorry.

The alternative is to either reimplement the dylibs, or to _recompile_ them; they're almost all open-source software, but that doesn't make it easy.
