### ISSUE TITLE
Pro Skater 2 crashes when starting the next heat in competition

### ISSUE THREAD

**Issue by thundergun1** [hikari-no-yume/touchHLE#251]
In the newest nightly build for Android, when playing Marseilles in career mode, the game crashes when trying to start the second heat of the competition. 

I understand that the nightly builds won't be officially supported and if this issue is known and is being corrected by the next full release I apologise, but i just thought I would flag it up.

**Comment by ciciplusplus** [comment]
Hi, please send us a crash log

**Comment by thundergun1** [comment]
[log.txt](https://github.com/hikari-no-yume/touchHLE/files/14388815/log.txt)
touchHLE v0.2.1-158-ga050b1d (git) — https://touchhle.org/

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::window: Accelerometer detected: lsm6dsm Accelerometer Non-wakeup.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 619
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/THPS2_v1.02_os221.ipa
App bundle info:
- Display name: THPS2
- Version: 1.02
- Identifier: com.activision.thps2
- Internal name (canonical): THPS2.app
- Minimum OS version: 2.2.1

Using options from touchHLE_default_options.txt for this app: --landscape-left --button-to-touch=DPadLeft,30,235 --button-to-touch=DPadUp,85,180 --button-to-touch=DPadRight,135,235 --button-to-touch=DPadDown,85,285 --button-to-touch=Start,240,30 --button-to-touch=A,395,280 --button-to-touch=B,445,230 --button-to-touch=X,345,230 --button-to-touch=Y,395,185
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: lsm6dsm Accelerometer Non-wakeup.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 619
touchHLE::mach_o: Loading armv6 slice for "THPS2"
touchHLE::mach_o: Loading armv6 slice for "libstdc++.6.dylib"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3f48a654 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef884), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef8b8), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150c94), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150da8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150dc0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150dd8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150df0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e08), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e20), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e38), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e50), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e68), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150e80), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150eb4), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150ee8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150f1c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150f50), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150f68), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150f80), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150fac), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150fb0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150fc8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150fe0), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x150ff8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x151010), 0x0, 0x1000) (unimplemented)
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x374f7b40 left unreplaced
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 619
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x374f7840 initWithContentURL:0x374f7830 (GuestPathBuf("/var/mobile/Applications/00000000-0000-0000-0000-000000000000/THPS2.app/ALLINTRO.m4v"))]
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x374f7840 play]
touchHLE::frameworks::uikit::ui_application: TODO: UIApplication's windows getter is returning only visible windows
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x374f7840 stop]
touchHLE::frameworks::av_audio::av_audio_player: TODO: [(AVAudioPlayer*)0x37cf29e0 setDelegate:0x374f7d40]
touchHLE::frameworks::av_audio::av_audio_player: TODO: [(AVAudioPlayer*)0x37ddf950 setDelegate:0x374f7d40]
Panic at src/frameworks/av_audio/av_audio_player.rs:106:5: assertion `left == right` failed
  left: -50
 right: 0
Register state immediately after panic:
	 R0: 0x37ddf950	 R1: 0x00166614	 R2: 0x00000001	 R3: 0x00000001
	 R4: 0x00000000	 R5: 0x0016f628	 R6: 0x0016e448	 R7: 0xfffffdd8
	 R8: 0x00000000	 R9: 0x3f490ed0	R10: 0x00000000	R11: 0x00000000
	R12: 0x00000000	 SP: 0xfffffdd8	 LR: 0x0014f590	 PC: 0x001514a4
Attempting to produce stack trace for main thread:
 0. 0x1514a4 (PC)
 1. 0x14f590 (LR)
 2. 0x142864
 3. 0x1034cc
 4. 0x1044bc
 5. 0x3b890
 6. 0x116cbc
 7. 0x117294
 8. 0x1175b4
 9. 0x117f98
10. 0x4318
11. [host function]
12. 0x3ca0
Next FP (0x0) is outside the stack.

**Comment by ciciplusplus** [comment]
Thanks, i may have an idea of a problem and a fix, but could please also share your save file so I can reproduce locally?
(save files are under `com.activision.thps2` folder of `touchHLE_sandbox`)

**Comment by thundergun1** [comment]
I get an EPERM (Operation not permitted) error in Zarchiver when i try and grab the save file from its folder

**Comment by thundergun1** [comment]
[THPS2 CAREER- Tony 2-23-24 17_26_35 $1050.zip](https://github.com/hikari-no-yume/touchHLE/files/14392113/THPS2.CAREER-.Tony.2-23-24.17_26_35.1050.zip)

I figured out how to bypass the aforementioned error, so here's the save. Just start the Marsailles level in Career and complete the first heat. The game should crash after selecting 'Next Heat'

**Comment by ciciplusplus** [comment]
I have a potential fix here https://github.com/hikari-no-yume/touchHLE/commit/7f3c9a33eb7f01e8e990af051f5b81bc9cf8ab17, please let me know if this fixes the issue for you

**Comment by thundergun1** [comment]
Hi Cici, can confirm 7f3c9a3 fixes this issue and I was able to finish the Marseilles stage in career.

I'll close this issue and if any more issues pop up during my playthrough I'll let you know. Thanks for fixing the issue so quickly

**Comment by thundergun1** [comment]
Just finished Tony's career so I can confirm the game is fully playable now, though a similar bug does occur in the Bullring competition.

Instead of crashing upon starting Heat 2 like in Marseilles, the game image freezes, though some sounds can still be heard. However, if you let the replay of your first heat play out fully then start heat 2, the game proceeds as normal and can be beaten. 

I'm not going to reopen the issue as the game is still playable, I just figured I'd make a note incase other players mention it. I will attach my save though just in case you want a look. Besides that and a few graphical bugs in Venice, the game works almost perfectly, thanks again.

[THPS2 CAREER- Tony 2-23-24 17_26_35 $1050.zip](https://github.com/hikari-no-yume/touchHLE/files/14393754/THPS2.CAREER-.Tony.2-23-24.17_26_35.1050.zip)
