### ISSUE TITLE
TouchLE for modern ios versions

### ISSUE THREAD

**Issue by chrispxxx** [hikari-no-yume/touchHLE#259]
I love what your team has picked together

The only thing I would request is a touchle port for modern ios versions.
Im sure it would actually even support more games do to similar software.

**Comment by luRaichu** [comment]
Modern iOS is 64-bit, and this project is aimed at older 32-bit versions instead.
I doubt touchHLE will support the latest iOS.

**Comment by ciciplusplus** [comment]
Hello,

Please check for existing issues before opening new ones:

- for running touchHLE on iOS https://github.com/hikari-no-yume/touchHLE/issues/74
- for supporting 64-bit apps https://github.com/hikari-no-yume/touchHLE/issues/181

Thanks
