### ISSUE TITLE
Emulator crashing when trying to load any game

### ISSUE THREAD

**Issue by ncojam** [hikari-no-yume/touchHLE#263]
When trying to run a game from the database, emulator just closing.
This is what I see in the Command Prompt, not including all the previous lines:
```
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL 4.0.0 - Build 10.18.10.5161 / Intel / Intel(R) HD Graphics 4000
thread 'main' panicked at 'Class "UIActivityIndicatorView" (0x3000aa50) is unimplemented. Call to class method "alloc".', src\objc\messages.rs:130:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Register state immediately after panic:
         R0: 0x3000aa60  R1: 0x0006cc28  R2: 0x3000bf20  R3: 0x00000028
         R4: 0x3000be50  R5: 0x0007ac34  R6: 0x0007a148  R7: 0xffffff0c
         R8: 0x3000beb0  R9: 0x00000000 R10: 0x00000000 R11: 0x00000000
        R12: 0x00002f05  SP: 0xfffffee8  LR: 0x0003bf5b  PC: 0x0006cae8
Attempting to produce stack trace for main thread:
 0. 0x6cae8 (PC)
 1. 0x3bf5b (LR)
 2. [host function]
 3. 0x2ecc
Next FP (0x0) is outside the stack.
```
Tried on Cave Bowling and Crash Bandicoot Nitro Kart 3D
Also tried NY_Nights, which is not in the database

**Comment by ciciplusplus** [comment]
@ncojam which version of touchHLE are you using?

**Comment by ciciplusplus** [comment]
> try download net 3.5+ and framework

touchHLE do not have .net as a dependency.
please stop suggesting things you have no idea about.

**Comment by ciciplusplus** [comment]
also, which versions of the games? do they align with one reported in the appdb as working? https://appdb.touchhle.org/

**Comment by ncojam** [comment]
> @ncojam which version of touchHLE are you using?

touchHLE v0.2.1
Crash Bandicoot Nitro Kart 3D v1.0.0
Not sure which version is Cave Bowling

Issue now can be closed, I tried another game from the database and it worked. So it's not the touchHLE problem.
