### ISSUE TITLE
Official Springboard support

### ISSUE THREAD

**Issue by drpatrikking** [hikari-no-yume/touchHLE#27]
Just an idea. As we can run the games with .app folder it would be cool if we would be able to run springboard like this.

**Comment by hikari-no-yume** [comment]
I'm not going to tempt fate by supporting pirating the OS itself.

**Comment by hikari-no-yume** [comment]
Though with that said: Yeah, it would be great to have a launcher that _resembles_ Springboard! I'll make an issue for that. :)
