### ISSUE TITLE
Doom Resurrection crashed

### ISSUE THREAD

**Issue by WarmestKrafter** [hikari-no-yume/touchHLE#272]
Doom Resurrection crashes after showing the game devs logo screen, and I don't know if the game is supported.

Device: POCO M5
TouchHLE version: 0.2.1

**Comment by ciciplusplus** [comment]
It is not.
Refer to compatibility db https://appdb.touchhle.org/ for currently supported games

Please read the text before opening issues:

> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:

> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
