### ISSUE TITLE
ARM64 Linux

### ISSUE THREAD

**Issue by corped12** [hikari-no-yume/touchHLE#277]
I tried using touchhle (it was like a month ago so version 0.2.1) on arm64 Linux with wine and that didn't work and I dont know how to build it

**Comment by ciciplusplus** [comment]
Linux is not an officially supported platform for us.
You can try to build on it using build instructions, but you're on your own here, good luck.

**Comment by corped12** [comment]
Turns out I just extracted it wrong it works with wine now ( touchhle version 0.2.2)
