### ISSUE TITLE
A pretty launcher for your app collection

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#28]
Perhaps something that resembles Springboard (the iOS home screen).

I think it would be cute if we could implement this using touchHLE's implementation of UIKit. That would require the UIKit implementation to be significantly improved of course. ;)

To be clear: we won't and _can't_ use iOS's actual launcher, and we should probably steer clear of imitating it too closely in look and feel, due to the legal hazard.

**Comment by hikari-no-yume** [comment]
I implemented a _very_ primitive graphical launcher in 3d3d8b02e83a644e0d516e68f332cd35c5f1928b. It's a temporary solution that just displays a simple message box with one button per app. Hopefully that's enough for most users for now. The main reason to add it was for the sake of the Android port, where there's no other way to launch apps.

**Comment by hikari-no-yume** [comment]
f547000c29ca58b974b506dbc460db41218b75e0 adds a much better app picker.

How's this for pretty? ^^
![Screenshot of a window for some version of touchHLE. The window dimensions are those of an original iPhone, in portrait. The window contains a grid of icons not dissimilar from the iOS home screen, but there is no status bar at the top or tray at the bottom. There are labelled icons for “Touch & Go”, ”CBNK 3D”, and fourteen copies of “Monkey Ball”. There is also a “Visit touchHLE.org” button at the bottom.](https://github.com/hikari-no-yume/touchHLE/assets/579774/966900ce-fa21-44cf-8329-1a87f083a39b)

**Comment by nighto** [comment]
Looks nice!
