### ISSUE TITLE
[Android] Cannot install newer apk releases on top of already installed ones.

### ISSUE THREAD

**Issue by Raypuia** [hikari-no-yume/touchHLE#280]
What it says on the tin.
This applies for both release and actions builds.
Perhaps an issue with the signing process?

**Comment by hikari-no-yume** [comment]
With the most recent release, v0.2.2, I changed how I was building and signing the APKs. However, I did specifically test that the release APKs (that is, versions v0.2.0, v0.2.1 and v0.2.2) should still be cleanly upgradeable without problems. They have all been manually signed with the same key, and they actually all have the same version number in the manifest, so Android should let you upgrade or even downgrade between them freely.

The automated builds from GitHub Actions are _not_ signed with that key however. So you can't upgrade/downgrade from one of the releases to one of the automated builds, and it might also be the case that you can't upgrade/downgrade between automated builds. This is to be considered expected. I don't want to trust GItHub with my signing key.

At least, this is what I believe the situation is. If you're upgrading between release APKs only, does it work?

**Comment by hikari-no-yume** [comment]
Just to make sure, I tested again on my testing device and sure enough, I was able to upgrade from v0.2.1 to v0.2.2, and downgrade from v0.2.2 to v0.2.1, without Android complaining and without loss of data.
