### ISSUE TITLE
Tales of phantasia iOS log.txt

### ISSUE THREAD

**Issue by Jace7352** [hikari-no-yume/touchHLE#282]
[log.txt](https://github.com/touchHLE/touchHLE/files/15018805/log.txt)
Thought use for reference later on

**Comment by ciciplusplus** [comment]
> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:

> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
