### ISSUE TITLE
TouchHLE won't open when connected to a tablet

### ISSUE THREAD

**Issue by Sean1220** [hikari-no-yume/touchHLE#286]
I tried to open TouchHLE on my Windows desktop with my drawing tablet connected(XP PEN Artist 15.6, has a screen display).
Opening the exe file, directly using the Powershell method, or dragging the IPA file into the exe file didn't open up the game screen.

I was confused for a second, and everything worked fine when I unplugged it.
I don't think this is something that must be fixed, but I am informing this issue if anyone wants to check out why this is happening.

**Comment by hikari-no-yume** [comment]
We probably can't debug this issue without the log output from PowerShell.

**Comment by Sean1220** [comment]
Anything that I can provide you with?
