### ISSUE TITLE
THPS2 Regression on Android

### ISSUE THREAD

**Issue by thundergun1** [hikari-no-yume/touchHLE#287]
In the newest Nightly build from last week (the one which added Dungeon Hunter) Tony Hawk 2 now crashes on startup. I've attached the log below.

[log.txt](https://github.com/touchHLE/touchHLE/files/15138354/log.txt)

**Comment by ciciplusplus** [comment]
Thanks for reporting!

It should be fixed with https://github.com/touchHLE/touchHLE/commit/4483ecebe91d2040190503da3d9c473df876a048, could you please confirm?

**Comment by thundergun1** [comment]
I can confirm it's fixed now. Thanks again for the quick response and fix 👍
