### ISSUE TITLE
Call Of Duty World At War Zombies doesn't work

### ISSUE THREAD

**Issue by YoiAlex** [hikari-no-yume/touchHLE#289]
Hi Hikari I want play COD WAW Zombies for iOs with TouchHLE but the game stops and in the tittle and I can't play , can you fix it? Thanks so much 🙏

**Comment by ciciplusplus** [comment]
This is not a supported app.
Please read the template message before opening any issues.

> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
