### ISSUE TITLE
The website is broken on Android in Chrome-based browsers

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#29]
Not sure if issues with the website belong in this repo, but it feels like a good place to put a notice about this as a reminder to myself, and so that fewer people ask me about it.

The site is made with Dashcode, which is software even more ancient than iPhone OS, so I'm not sure how easy this is to fix.

By the way: if you have an Android phone and know how to use the Chrome developer tools with it, I'd really appreciate getting a copy of the debug log. Even better, if you happen to be skilled with JS/DOM debugging and can tell me what the underlying issue is, that'd be great!

**Comment by juraisa** [comment]
It works if I switch to desktop mode on Android

**Comment by hikari-no-yume** [comment]
Yep, I've heard about that also, it's weird that that fixes it…

**Comment by parkerlreed** [comment]
As for the actual console log not much

![image](https://user-images.githubusercontent.com/841440/216792170-23d3ebec-4a70-4216-9a93-c68994b06b59.png)

Tapping isn't producing any errors. I was starting to think there may be an invisible blocking element preventing the taps but nothing seems apparent. I'll keep poking.

![image](https://user-images.githubusercontent.com/841440/216792263-4ea8b149-54d0-4dda-846e-ea33baf80b3e.png)

**Comment by hikari-no-yume** [comment]
FWIW that /mobile/null thing happens on desktop too so it's something unimportant.

**Comment by parkerlreed** [comment]
Chrome is aware of the elements being tapped. 

![image](https://user-images.githubusercontent.com/841440/216792726-f2816118-c723-4734-92dc-61d3f39694b1.png)

**Comment by hikari-no-yume** [comment]
There's a really simple JS file (the only one I partly wrote myself, the rest is auto-generated) that is supposed to contain the onclick handler, or something like that, for the list elements. If you can easily locate that file, you might want to set a breakpoint on the function to see if it gets run.

**Comment by parkerlreed** [comment]
The damndest thing... I have a breakpoint control panel in the upper right but I seemingly cannot set any line as a breakpoint 
![image](https://user-images.githubusercontent.com/841440/216793112-7ef5074e-5c38-4a0b-bafb-47400a55e8d4.png)

EDIT: It moved to clicking the line number... Very intuitive Google...

**Comment by hikari-no-yume** [comment]
Huh. It's a global function, so maybe you can like, replace it with a different function that throws an exception or something, before the page finishes loading? You might have to download the site and mirror it locally for that though.

**Comment by parkerlreed** [comment]
function itemClicked(event) gets called on desktop layout and hits the breakpoint. 

Never makes it there on mobile view

**Comment by hikari-no-yume** [comment]
Cool, so the problem must be inside the more low-level event handler set up by the list view, I guess.

**Comment by puckipedia** [comment]
It looks like the onclick handler is not actually registered at any point when running on mobile chrome; instead, it seems to be shimmed by DashCode. However, due to a funny set of circumstances (mobile chrome looks like MobileSafari, and document.createTouch is deprecated) it seems it just .. doesn't register the touch handler.

If you manually override the code to set `DC.Browser.MobileSafari` to false, everything works roughly as intended.

**Comment by hikari-no-yume** [comment]
@puckipedia Thanks for figuring this out! I've finally added a workaround for this, and now the site works on my recently acquired Android phone in Chrome, and also in Chrome on my MacBook when in the responsive design testing mode. Overriding `DC.Browser` seemed like it'd be tricky due to load order, so I just spoofed the user agent instead.
