### ISSUE TITLE
Issue with loading the fonts on Intel Mac

### ISSUE THREAD

**Issue by EyexPro** [hikari-no-yume/touchHLE#290]
I am having a problem upon starting the touchHLE unix file on Mac. I get the following error messages: 

touchHLE::window: Driver info: OpenGL 2.1 INTEL-20.7.2 / Intel Inc. / Intel(R) Iris(TM) Plus Graphics 640
thread 'main' panicked at src/font.rs:76:13:
Couldn't read bundled font file "touchHLE_fonts/LiberationSans-Regular.ttf": No such file or directory (os error 2). Perhaps the directory is missing?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Could anyone help me solve this problem?

**Comment by hikari-no-yume** [comment]
> Perhaps the directory is missing?

This is the problem. touchHLE comes with certain bundled files (fonts, dynamic libraries, default options). You must extract the whole content of the ZIP file, not just the touchHLE executable, and you should keep the files together.

If you are using one of the unstable testing builds from GitHub Actions, you need to extract the ZIP file from a stable release first.

**Comment by EyexPro** [comment]
Thank you so much for the quick reply! I have extracted all the files already, the fonts are there in the folder, but the error message still pops up. Can you send me a link for a stable release?

**Comment by hikari-no-yume** [comment]
https://github.com/touchHLE/touchHLE/releases

**Comment by EyexPro** [comment]
Yes, this is the same one that I am trying to use, the latest release. 
<img width="676" alt="Képernyőfotó 2024-04-29 - 15 42 21" src="https://github.com/touchHLE/touchHLE/assets/168443507/d6ab9ef2-1a96-409c-98c0-3b9496c449ca">

**Comment by hikari-no-yume** [comment]
How are you running it?

**Comment by ciciplusplus** [comment]
Hi,
Could you please share as well what your launch command?

**Comment by EyexPro** [comment]
I am trying to run the touchHLE unix file (exec) by clicking on it. If this is the wrong way to do it, please let me know.

**Comment by hikari-no-yume** [comment]
Uhh… that _should_ work. I wonder if this is falling afoul of modern macOS trying to sandbox stuff downloaded from the internet.

If you right click on it and click Open, what happens?

**Comment by EyexPro** [comment]
So, when I opened it initially, gatekeeper stepped in, but I could overwrite it in the settings, and launch the executable. I can see from the log that it tries to build the app selector interface, but it stops at the problem with the fonts, and gives the error message.

**Comment by hikari-no-yume** [comment]
Okay, I want to check something… if you open Terminal and type `xattr -d com.apple.quarantine ` (include the final space, don't press enter), then drag and drop the `touchHLE` file into the window, then press Enter… does the problem disappear?

**Comment by EyexPro** [comment]
Thank you for the suggestion, but sadly, I am still getting the same error. I am also receiving the "No such xattr: com.apple.quarantine" error in terminal or the "Not enough arguments for option -d. Expected at least 2 but got 1" error

**Comment by EyexPro** [comment]
<img width="568" alt="Képernyőfotó 2024-04-30 - 8 49 17" src="https://github.com/touchHLE/touchHLE/assets/168443507/6a670647-9c3a-4115-8827-d742b9957fbc">

**Comment by nighto** [comment]
Googling this error, you might want to try this:

```codesign --force --deep --sign - /path/to/touchHLE.app```

via: https://stackoverflow.com/a/64985297/1110655

**Comment by hikari-no-yume** [comment]
Are you on macOS Ventura?

**Comment by EyexPro** [comment]
Nighto, thank you for the suggestion, sadly, still the same error. I am on Ventura, with no future upgrade path, this is the latest supported MacOS on my machine.

**Comment by hikari-no-yume** [comment]
Okay, my suggestion is to open a Terminal window, type `cd ` (including the space), drag the folder containing touchHLE into the terminal, press enter, then type `./touchHLE` and press enter again

**Comment by EyexPro** [comment]
This is working! The app picker just opened. I could not get my Tower Bloxx New York .ipa to run, but this is still up to a great start. Thank you so much for the quick support

**Comment by Jamirus238** [comment]
> 
> This is the problem. touchHLE comes with certain bundled files (fonts, dynamic libraries, default options). You must extract the whole content of the ZIP file, not just the touchHLE executable, and you should keep the files together.
> 
Are Asian language fonts expected to be a problem? The file picker refuses to come up for me when certain apps are in the directory (tested on Windows & Android), a commonality seems to be some sort of Japanese/English content. 
![ErrorTouchHle](https://github.com/touchHLE/touchHLE/assets/56701184/e9e9e721-082f-4133-b773-c48d53ec8424)

**Comment by hikari-no-yume** [comment]
Please file a separate issue for that rather than commenting on this one. It's not the same issue.

**Comment by rachelombok** [comment]
when I double click on the touchHLE.exec file it also gives me this error related to the font, but when using the `./touchHLE` command instead in my terminal it does not appear

**Comment by hikari-no-yume** [comment]
There is no file called `touchHLE.exec`.

**Comment by hikari-no-yume** [comment]
Oh, I can reproduce the issue with double-clicking not working. Maybe it has to be run from the Terminal :/

I can try to fix that in the next release.

**Comment by rachelombok** [comment]
Sorry wrong verbiage, when I click on the touchHLE exec file on mac, I get the error related to the font that OP described

**Comment by perkunas34** [comment]
> Okay, my suggestion is to open a Terminal window, type `cd ` (including the space), drag the folder containing touchHLE into the terminal, press enter, then type `./touchHLE` and press enter again

I did this, it worked, i successfully opened the touchHLE app but when I touch Asphalt 5 icon, app disappears.

**Comment by nighto** [comment]
@perkunas34 it might me crashing for whatever other reason, please check the logs to be sure what the problem might be.

**Comment by hikari-no-yume** [comment]
If you downloaded a preview release of touchHLE, you will need to extract it into the same directory as a normal release.

**Comment by hikari-no-yume** [comment]
I am hiding these comments because they are likely to be off-topic. Most likely you are using the wrong version of touchHLE. https://touchhle.org/download/

**Comment by hikari-no-yume** [comment]
As of the latest preview build (https://touchhle.org/download/), touchHLE for macOS now comes packaged in `.app` bundle form in a `.dmg`. What that means in practice is that all these problems with getting it running should now be solved. You don't need to do anything in the Terminal, you can drag touchHLE into the Applications folder and it should “just work” so long as you can get past the Gatekeeper prompt.
