### ISSUE TITLE
How to fund?

### ISSUE THREAD

**Issue by JordanPlayz158** [hikari-no-yume/touchHLE#293]
I was looking through the readme and contributing file but didn't see a place for funding, do you guys support funding as I would like to help out this project so hopefully games like Zombie Farm aren't lost to time.

**Comment by hikari-no-yume** [comment]
Personally, I previously accepted donations, but I have stopped doing this. It wasn't enough to cover my living expenses, so it couldn't replace a job, and it creates an expectation I will spend a significant amount of my time on the project, which I was no longer managing to do.

I don't know how other contributors feel.

**Comment by JordanPlayz158** [comment]
Yeah, that is fair, same reason I don't accept donations on my projects. Just asked as my brother was gonna go get an old Apple device to play it (Zombie Farm) but thought it would do infinitely more good on a project like this one but I completely understand, thanks for getting back to me so quickly!

**Comment by ciciplusplus** [comment]
I think it would be nice to have "support project" or "tip a developer" functionality associated to the touchHLE.

But this should not be considered as "pay to make game X work", but as "appreciate your work, here is a tip"

**Comment by hikari-no-yume** [comment]
@H1W0XXX While we appreciate contributions to touchHLE (please submit patches on Gerrit and make a pull request), we have had a lot of problems with forks, so please do not use our GitHub page to promote your own fork. This is your one and only warning.
