### ISSUE TITLE
Feature Suggestion : Adding popups

### ISSUE THREAD

**Issue by corped12** [hikari-no-yume/touchHLE#296]
I believe some apps don't work due to a "Agree to our Terms of service & Privacy Policy" popup

**Comment by ciciplusplus** [comment]
This is an app specific feature
Please read the template message before opening any issues.

> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> 
> You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
