### ISSUE TITLE
Add supoort

### ISSUE THREAD

**Issue by xdatsec** [hikari-no-yume/touchHLE#300]
I can't load certain apps and I look for logs it shows libz.1.dylib where it says it is missing, , is it possible to add this to android build?

**Comment by hikari-no-yume** [comment]
Please stop opening issues about non-working apps. As the text that you must read before posting an issue says, we do not want issues about non-working apps, there is an almost infinite number of them.

**Comment by xdatsec** [comment]
Ok it seems ill fix it with my own
