### ISSUE TITLE
Süper sepernutural 😁😁

### ISSUE THREAD

**Issue by postal12** [hikari-no-yume/touchHLE#311]

**Comment by hikari-no-yume** [comment]
?

**Comment by postal12** [comment]
Please let me know when iPhone 3.0 will be released.

**Comment by hikari-no-yume** [comment]
iPhone OS 3.0 support is already released.

**Comment by postal12** [comment]
resident evil degeneration sparta 2 hero doom resurrection not opening please

**Comment by postal12** [comment]
resident evil degeneration sparta 2 hero doom resurrection not opening please

**Comment by hikari-no-yume** [comment]
> Please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.

**Comment by postal12** [comment]
> iPhone OS 3.0 support is already released.

resident evil degeneration sparta 2 hero doom resurrection not opening please
