### ISSUE TITLE
Doom 2 RPG Requires both hands to enter the game with repeated tapping and Crashes if you try to use the map or enter the menu with that method.

### ISSUE THREAD

**Issue by Tatsu09** [hikari-no-yume/touchHLE#312]
Single tapping does not work and is not registered so you must tap fast with two fingers repeatedly to enter the game.

Once in it works except the options at the bottom of the screen require the same method to use it. If you do it on the map or menu the game crashes.

The same issue exists for WolfensteinRPG but only In the main menu it works flawlessly outside that.

**Comment by ciciplusplus** [comment]
Hi, could you please provide the crash log?
Otherwise, the issue was already reported here https://github.com/touchHLE/touchHLE/issues/184
