### ISSUE TITLE
Loading on macOS Sonoma

### ISSUE THREAD

**Issue by SodaPop81** [hikari-no-yume/touchHLE#314]
If for arguments sake my file is named "WrestleFest.app" and it is located in the same folder as touchHLE what do I need to type in terminal to get it to launch. I am getting this error:

Warning: app requires OS version 5.0. Only iPhone OS 2.x and iPhone OS 3.0 apps are currently supported.
No options found for this app in touchHLE_default_options.txt
No options found for this app in touchHLE_options.txt

touchHLE::environment: Warning: Could not read icon file
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 2.1 Metal - 88.1 / Apple / Apple M3 Pro
touchHLE::mach_o: Loading armv7 slice for "WrestleFest Premium"
touchHLE::mach_o: Warning! DyldInfo is not handled.
touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
touchHLE::mach_o: Loading armv6 slice for "libstdc++.6.dylib"
thread 'main' panicked at src/dyld.rs:277:18:
not implemented

Is this just not working because nothing is simulating OS 5.0?

**Comment by ciciplusplus** [comment]
You already have answer to your question:

> Only iPhone OS 2.x and iPhone OS 3.0 apps are currently supported.

Please also read the text before opening the issues.
