### ISSUE TITLE
bug screen 2010 World map

### ISSUE THREAD

**Issue by makaher** [hikari-no-yume/touchHLE#318]
intro and bug scren
![Screenshot_20240616-164632](https://github.com/touchHLE/touchHLE/assets/171063954/978b7c67-d2d2-4b73-9dca-68a72aa74b2d)

touchHLE v0.2.2-71-ge46a3e8 — https://touchhle.org/

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/2010 World Map 1.6.ipa
App bundle info:
- Display name: 2010 Map
- Version: 1.6
- Identifier: com.appventions.worldmap
- Internal name (canonical): WorldMap.app
- Minimum OS version: 2.0

No options found for this app in touchHLE_default_options.txt
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 308
touchHLE::mach_o: Loading armv6 slice for "WorldMap"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
CPU emulation begins now.
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x3000cab0 left unreplaced
touchHLE::frameworks::uikit::ui_touch: Couldn't find a view for touch at CGPoint { x: 220.58255, y: 559.1117 } in window 0x3000cc30, discarding

**Comment by hikari-no-yume** [comment]
I guess this is a UIKit-heavy app and that's why it doesn't work. Cool that it doesn't immediately crash.

**Comment by makaher** [comment]
> I guess this is a UIKit-heavy app and that's why it doesn't work. Cool that it doesn't immediately crash.

I think this is true since the application is a world map in 2010 and the emulator cannot recreate this. I thought that the problem was in the computer, but when I tested it on the phone now I realized that it was a problem with the emulator. perhaps the application works because on the right there is a white cube in the form of an artifact

**Comment by ciciplusplus** [comment]
I think this kind of issue is more appropriate as a submission to the appdb.
I'll close it as it is nor regression nor a bug.
