### ISSUE TITLE
[Question] Do linking free apps count as piracy

### ISSUE THREAD

**Issue by upintheairsheep** [hikari-no-yume/touchHLE#32]
Does putting links to iOS apps that are known to have always been free count as piracy or are they allowed?

**Comment by hikari-no-yume** [comment]
It's still piracy from a legal perspective even if the app was being distributed for free, unless the app developer has given explicit permission.

**Comment by upintheairsheep** [comment]
That fact just confuses me. But if it’s some really old app from the App Store that’s still up does it count

**Comment by hikari-no-yume** [comment]
Yes. I mean, the developer probably won't care, but it's still a potential legal problem.

Copyright law isn't about whether you get something for free, it's about whether you have permission. Unless you've been explicitly given permission, you don't have it.

**Comment by upintheairsheep** [comment]
What about if it is from an Open Directory confirmed to be by the official creator

**Comment by hikari-no-yume** [comment]
Uh… if that means the creator's given explicit permission for it to be archived, _and_ that creator holds all the relevant copyrights on the app, then it's fine.
