### ISSUE TITLE
Thumpies XL 1.0.0 crashes

### ISSUE THREAD

**Issue by idontwannaforgetmyusernameorpassword** [hikari-no-yume/touchHLE#324]
It shows the BBB logo, then crashes.

**Comment by ciciplusplus** [comment]
Read the text before opening issues:

> Also, please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about broken apps unless one of these applies:
>
> - You know that this specific version of the app worked in a previous version of touchHLE and you can reproduce this.
> - The app is partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.

**Comment by idontwannaforgetmyusernameorpassword** [comment]
You see, the thing is, I **was** going to add it to the app compatibility database, but it's asking for the app bundle and GPU, both of which I don't know.

**Comment by nighto** [comment]
The app bundle appear on emulator logs in command line, and the GPU model you need to check on your own computer settings

**Comment by idontwannaforgetmyusernameorpassword** [comment]
The command line instantly disappears, and I'm pretty sure no log files are made. Also, I have scoured all of my settings and couldn't find my GPU info.

**Comment by nighto** [comment]
If you are running on PC, you can execute touchHLE.exe from command line manually (instead of double-clicking it) and choose the game from app picker, so the logs on stdout are kept.

**Comment by idontwannaforgetmyusernameorpassword** [comment]
And for the GPU?

**Comment by hikari-no-yume** [comment]
GPU info is also in the log.
