### ISSUE TITLE
Touchhle still doesn't work for PowerVR Android

### ISSUE THREAD

**Issue by Shartrizard** [hikari-no-yume/touchHLE#328]
### Describe the feature or issue.

The white screen issue for PowerVR Androids is still up. I'm sorry if you're still working on fixing it and this annoys you but i just thought that putting this up for other people is alright, some might not know this is still a problem.

### By submitting this issue, I certify that…

- [x] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
Duplicate of https://github.com/touchHLE/touchHLE/issues/200
