### ISSUE TITLE
Can not be executed in Android emulator LDPlayer9.

### ISSUE THREAD

**Issue by sniperhgy** [hikari-no-yume/touchHLE#332]
### Describe the feature or issue.

Although it can be installed normally in the Android emulator LDPlayer 9, but it cannot be executed. After clicking the app, it crashes directly.

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
On which platform are you running?

**Comment by sniperhgy** [comment]
> On which platform are you running?

Hi ciciplusplus, thank you for your concern. I'm using Windows 7 64 bit, the LDPlayer 9 is also 64 bit, android 7 is the kernel.

**Comment by ciciplusplus** [comment]
On Windows you already have x86 binaries of touchHLE, I don't see the issue here.

**Comment by sniperhgy** [comment]
> ciciplusplus

The touchHLE windows version can't run the game on my Windows 7😂，once I click the icon of the game, it will raise up a lot of error messages then quit.

**Comment by sniperhgy** [comment]
My video card is Nvidia 760 GTX, have 8GB memory and CPU is Intel i7 with 3.6 GHz.

**Comment by hikari-no-yume** [comment]
Which app isn't working?

**Comment by sniperhgy** [comment]
> Which app isn't working?

touchHLE android version isn't working on the android emulator LDPlayer 9 (a software can execute android apps on PC).

**Comment by hikari-no-yume** [comment]
I mean, what app are you trying to run in touchHLE?

Based on what you have said, the screen with the app icons shows up. So it sounds like touchHLE does actually work, and the problem might be you are trying to run an unsupported app.

**Comment by sniperhgy** [comment]
> I mean, what app are you trying to run in touchHLE?
> 
> Based on what you have said, the screen with the app icons shows up. So it sounds like touchHLE does actually work, and the problem might be you are trying to run an unsupported app.

Sorry about that, I took a misunderstanding. I tried to execute "Zombie infection", which requires iOS version 2.2.1, please check the error logs in attachment.
[result.txt](https://github.com/user-attachments/files/16159802/result.txt)

**Comment by hikari-no-yume** [comment]
According to https://appdb.touchhle.org/apps/347 this game has not been tested on the v0.2.2 stable release of touchHLE, so that is probably your problem. You can try a recent preview build like https://github.com/touchHLE/touchHLE/actions/runs/9863992707 but we won't provide support. I hope this helps.

**Comment by sniperhgy** [comment]
Sure, got it, thank you. But in this time, the latest version of touchHLE can't be executed in my Windows 7 environment
![捕获](https://github.com/touchHLE/touchHLE/assets/13534439/fc62e588-aa23-4f68-9622-7ac5d6847267)
