### ISSUE TITLE
Windows 11 Build Error When Building for Windows

### ISSUE THREAD

**Issue by TheUltimateOrion** [hikari-no-yume/touchHLE#334]
When running `cargo run --release`, it goes through most of the process until its near the end where it says:
failed to run custom build command for `touchHLE_openal_soft_wrapper v0.2.2 (C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\src\audio\openal_soft_wrapper)`

Caused by:
  process didn't exit successfully: `C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-8802e86bd872cad6\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\aarya\\OneDrive\\Documents\\Programming\\touchHLE\\src\\audio\\openal_soft_wrapper\\../../..\\vendor/openal-soft" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DLIBTYPE=STATIC" "-DALSOFT_UTILS=OFF" "-DALSOFT_NO_CONFIG_UTIL=ON" "-DALSOFT_EXAMPLES=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\aarya\\OneDrive\\Documents\\Programming\\touchHLE\\target\\release\\build\\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\\out\\windows" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"
  -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
  -- The C compiler identification is MSVC 19.40.33812.0
  -- The CXX compiler identification is MSVC 19.40.33812.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - broken
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.

  CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:67 (message):
    The C compiler

      "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: 'C:/Users/aarya/OneDrive/Documents/Programming/touchHLE/target/release/build/touchHLE_openal_soft_wrapper-ae14e493d1aea70e/out/windows/build/CMakeFiles/CMakeScratch/TryCompile-ipphjq'

      Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_22e19.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
      MSBuild version 17.10.4+10fbfbf2e for .NET Framework
      Build started 2024-07-19 7:40:50 PM.

      Project "C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "cmTC_22e19.dir\Debug\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\Debug\".
        Creating directory "cmTC_22e19.dir\Debug\cmTC_22e19.tlog\".
      InitializeBuildStatus:
        Creating "cmTC_22e19.dir\Debug\cmTC_22e19.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "cmTC_22e19.dir\Debug\cmTC_22e19.tlog\unsuccessfulbuild".
      ClCompile:
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\CL.exe /c /Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D "CMAKE_INTDIR=\"Debug\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_22e19.dir\Debug\\" /Fd"cmTC_22e19.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue  -Brepro "C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\testCCompiler.c"
        testCCompiler.c
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.dir\Debug\cmTC_22e19.tlog'. [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.DeleteFiles(ITaskItem[] filesToDelete) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      Done Building Project "C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj" (default targets) -- FAILED.

      Build FAILED.

      "C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj" (default target) (1) ->
      (ClCompile target) ->
        C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.dir\Debug\cmTC_22e19.tlog'. [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.DeleteFiles(ITaskItem[] filesToDelete) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\aarya\OneDrive\Documents\Programming\touchHLE\target\release\build\touchHLE_openal_soft_wrapper-ae14e493d1aea70e\out\windows\build\CMakeFiles\CMakeScratch\TryCompile-ipphjq\cmTC_22e19.vcxproj]

          0 Warning(s)
          1 Error(s)

      Time Elapsed 00:00:00.65

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:56 (project)

  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', C:\Users\aarya\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.49\src\lib.rs:1104:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by ciciplusplus** [comment]
We haven't tested building on Win11, only Win10.

From the logs it seems like you're using OneDrive path `C:\Users\aarya\OneDrive\Documents`.
Is it something Win11 related? Like, everything is synced to OneDrive? Can you try to build in non-OneDrive folder?

**Comment by TheUltimateOrion** [comment]
Yes, that was it. It seems to build successfully now once it is in a non Onedrive folder.

**Comment by ciciplusplus** [comment]
cool 😃
