### ISSUE TITLE
touchHLE crashing and not creating log files on Windows 11

### ISSUE THREAD

**Issue by lucebreaks** [hikari-no-yume/touchHLE#337]
### Describe the feature or issue.

The title pretty much says it all.
I'll try to start known working apps, and they crash immediately and don't create a log file at all.

Running the latest touchHLE version 0.2.2

I'm running a 13th Gen i5 and an RTX 4060

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
Do you have logs if you run the touchHLE via a command line terminal?

**Comment by lucebreaks** [comment]
> Do you have logs if you run the touchHLE via a command line terminal?

Told me something about encrypted apps
hmmm

**Comment by hikari-no-yume** [comment]
As it says in the README, apps must be decrypted for touchHLE to be able to run them.

**Comment by lucebreaks** [comment]
> As it says in the README, apps must be decrypted for touchHLE to be able to run them.

Ahh right I didn't see that at first.
I was hoping some of the apps I had already archived would work but I suppose not, hmmmm, I unfortunately don't have my iphone with me to get the apps off of it directly.
