### ISSUE TITLE
The game does not see the function in the code, but it is there

### ISSUE THREAD

**Issue by gamelover-sergei** [hikari-no-yume/touchHLE#338]
### Describe the feature or issue.

its fileSystemRepresentation, it is in the code, but the game does not see it

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
Which game?
Do you have a crash log?

**Comment by hikari-no-yume** [comment]
I don't see a function named fileSystemRepresentation.

**Comment by gamelover-sergei** [comment]
> I don't see a function named fileSystemRepresentation.

![IMG_1293](https://github.com/user-attachments/assets/0b326ce0-1e0e-40de-a5b2-6ba5358cbd41)

**Comment by gamelover-sergei** [comment]
> Which game? Do you have a crash log?

touchHLE PREVIEW v0.2.2-162-gfd1f24e — https://touchhle.org/
Built from branch "trunk" of "touchHLE/touchHLE" by GitHub Actions workflow run https://github.com/touchHLE/touchHLE/actions/runs/10126679591.

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::app_picker: Warning: couldn't load icon for app bundle /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/Chewie Chu FREE [Ludigames] (v1.0 LP os21).rc325.ipa: Could not read icon file (displaying placeholder instead)
touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 505
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/Zen_Bound_v1.2.2.ipa
App bundle info:
- Display name: Zen Bound
- Version: 1.2.2
- Identifier: com.secretexit.zenbound
- Internal name (canonical): Zen Bound.app
- Minimum OS version: 2.2

No options found for this app in touchHLE_default_options.txt
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: BMA255 Accelerometer/Temperature/Double-tap.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 505
touchHLE::mach_o: Loading armv6 slice for "Zen Bound"
touchHLE::mach_o: Loading armv6 slice for "libstdc++.6.dylib"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3f48a654 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef884), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef8b8), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x41d8c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x41d80), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x41d88), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x41d84), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x41d90), 0x0, 0x1000) (unimplemented)
touchHLE::frameworks::openal: App wants to set mixer output sample rate to 44100 Hz
Panic at src/objc/messages.rs:60:13: Object 0x374fa390 (class "_touchHLE_NSString", 0x374f7190) does not respond to selector "fileSystemRepresentation"!
Register state immediately after panic:
	 R0: 0x374fa390	 R1: 0x00045a68	 R2: 0x00000000	 R3: 0x0000d950
	 R4: 0x00000000	 R5: 0x00000000	 R6: 0x00000000	 R7: 0xffff633c
	 R8: 0x00000000	 R9: 0x3f490ed0	R10: 0x374fa380	R11: 0x00000000
	R12: 0x0004f0e8	 SP: 0xffff6328	 LR: 0x00040dec	 PC: 0x0004252c
Attempting to produce stack trace for main thread:
 0. 0x4252c (PC)
 1. 0x40dec (LR)
 2. 0x3f824
 3. 0x2df8
 4. 0x2a40
Next FP (0x0) is outside the stack.

**Comment by ciciplusplus** [comment]
The game needs a NSString's filesystem representation getter method https://developer.apple.com/documentation/foundation/nsstring/1414559-filesystemrepresentation?language=objc

This is not implemented and the game in question is not supported.
