### ISSUE TITLE
Give touchhle ui a background

### ISSUE THREAD

**Issue by DrPonx** [hikari-no-yume/touchHLE#342]
### Describe the feature or issue.

U can give the ui where u go into your games a background, it could help give touchhle personality and make it look less bare bones no offense, also u can make it look iPod touch nostalgic like for the background for fun 

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by Marquinbr** [comment]
Grat

**Comment by Marquinbr** [comment]
Great

**Comment by Marquinbr** [comment]
Dldk

**Comment by Marquinbr** [comment]
Kfjd

**Comment by Marquinbr** [comment]
Xkxkd

**Comment by Marquinbr** [comment]
Xkxkx

**Comment by Marquinbr** [comment]
Xixi

**Comment by Marquinbr** [comment]
Xkxk

**Comment by Marquinbr** [comment]
Ckxkxi

**Comment by Marquinbr** [comment]
Didid

**Comment by Marquinbr** [comment]
Dkxidi

**Comment by Marquinbr** [comment]
Dkdkdi

**Comment by Marquinbr** [comment]
Xixix

**Comment by Marquinbr** [comment]
Xkxkx

**Comment by Marquinbr** [comment]
Xkxkxi

**Comment by Marquinbr** [comment]
Kxkxk

**Comment by Marquinbr** [comment]
Xkxjic

**Comment by Marquinbr** [comment]
Kxkxkx

**Comment by Marquinbr** [comment]
Xjxkdi

**Comment by Marquinbr** [comment]
Xkxid

**Comment by Marquinbr** [comment]
Didiid

**Comment by Marquinbr** [comment]
Dkdkoddi

**Comment by Marquinbr** [comment]
Xkxkxi

**Comment by Marquinbr** [comment]
Xjckci

**Comment by Marquinbr** [comment]
Xjxjcj

**Comment by Marquinbr** [comment]
Dkdkdi

**Comment by Marquinbr** [comment]
Kddodk

**Comment by hikari-no-yume** [comment]
c7aa12e141952fa1e778f2dd767deb8ab22dd308
