### ISSUE TITLE
Build for aarch64/arm64 linux ex: Droidian/Ubuntu touch

### ISSUE THREAD

**Issue by jhay06** [hikari-no-yume/touchHLE#344]
### Describe the feature or issue.

I tried cargo build --target aarch64-unknown-linux-gnu 
but it fail on finding crate for core 

error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-unknown-linux-gnu`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.

already added aarch64-unknown-linux-gnu on rustup 
also installed the aarch64-linux-gnu gcc 

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by jhay06** [comment]
okay finally found out how but got i think the last error that  should fix 

= note: /usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: cannot find -lsndio: No such file or directory
          collect2: error: ld returned 1 exit status

**Comment by ciciplusplus** [comment]
This issue https://github.com/touchHLE/touchHLE/issues/3 could be helpful for you
