### ISSUE TITLE
Wil be there a real iOS support?

### ISSUE THREAD

**Issue by Samuel525432** [hikari-no-yume/touchHLE#350]
### Describe the feature or issue.

I was wondering can be there a iOS support for touchHLE?
What I mean is can be a iOS support for iPhone and iPads?

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
duplicate https://github.com/touchHLE/touchHLE/issues/74
