### ISSUE TITLE
Not working on android 5.1.1

### ISSUE THREAD

**Issue by Coolbooter** [hikari-no-yume/touchHLE#352]
### Describe the feature or issue.

Hi my phone is a 2015 Samsung galaxy grand prime with android 5.1.1 is not working right
now so pls fix it pls

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
Your phone is very old and probably not powerful enough to run touchHLE. We will not fix it. Sorry.
