### ISSUE TITLE
Is Fastlane only for TouchHLE Android

### ISSUE THREAD

**Issue by iplayfastandfurious** [hikari-no-yume/touchHLE#356]
### App DB report link

I am not sure

### App name

Fastlane Street Racing

### App version

2.0

### touchHLE version

v0.2.2

### Operating system

Windows 11

### GPU

NVDIA GTX 4090

### What is the problem with the app?

I have tried playing Fastlane on Windows, but I am not sure how to make the cars turn. Is this game only meant for android os? Or is there a way to control the cars?

### By submitting this issue, I certify that…

- [X] I have tested that this version of this app is at least partially working in a previous version of touchHLE.
- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
Please read the README that with the release of touchHLE you downloaded. It explains the controller options.
