### ISSUE TITLE
Windows version launch panic

### ISSUE THREAD

**Issue by qiaoranMC** [hikari-no-yume/touchHLE#357]
### App DB report link

Unknown

### App name

touchHLE.exe

### App version

Unknown

### touchHLE version

Unknown

### Operating system

Windows 10 22H2

### GPU

Unknown

### What is the problem with the app?

Try launch release the windows version auto exit
Application can not launch

### If touchHLE crashed, please paste the log output.

```text
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-09-01T09:06:54.4936867Z" /> 
  <EventRecordID>4561</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>SVOCVUIXNWBW0FG</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>touchHLE.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>660b1b99</Data> 
  <Data>touchHLE.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>660b1b99</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000108baf</Data> 
  <Data>1e08</Data> 
  <Data>01dafc4e4917ac53</Data> 
  <Data>C:\Users\Administrator\Desktop\emu\touchHLE.exe</Data> 
  <Data>C:\Users\Administrator\Desktop\emu\touchHLE.exe</Data> 
  <Data>d5a35a06-5c90-4830-8fbe-52cc3b736ed2</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

### By submitting this issue, I certify that…

- [X] I have tested that this version of this app is at least partially working in a previous version of touchHLE.
- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
We cannot help you if we don't know what version of touchHLE you are using. Also, that log output isn't useful to us, please run touchHLE from a command prompt and then show us the output.

**Comment by qiaoranMC** [comment]
touchHLE version:later

**Comment by qiaoranMC** [comment]
Launch the game:Flyme2themoon
This is a mihoyo game

**Comment by hikari-no-yume** [comment]
Nobody has reported this game as working, so it is not considered a supported title.
