### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by Rafikingbro** [hikari-no-yume/touchHLE#36]
Hello i have been using your emulator and its pretty good, can you pleeease make an andriod port uwu

**Comment by p0008874** [comment]
> Hello i have been using your emulator and its pretty good, can you pleeease make an andriod port uwu

The emulator still very early state when you asked at beginning.

**Comment by hikari-no-yume** [comment]
Yeah, it's still early days for this project. For now, I'm more interested in getting some more games working, and making various other enhancements. Porting to Android will be a bit annoying, but it's absolutely something I will attempt at some point.

**Comment by hikari-no-yume** [comment]
Android support is now on trunk: b7792fa77351da821b7d2e9bde398de7c00af39b. This is mostly the work of @ciciplusplus. A few things need fixing still but I'm hoping to make a release later this month.
