### ISSUE TITLE
(This issue can be deleted)

### ISSUE THREAD

**Issue by iplayfastandfurious** [hikari-no-yume/touchHLE#364]
### App DB report link

(Not Sure)

### App name

FF53D/ Fast and Furious Pink Slip

### App version

Versions 1.0.2 and 1.0.3

### touchHLE version

v0.2.2

### Operating system

Android

### GPU

(Not Sure)

### What is the problem with the app?

The game runs very well. Heck, even better than on iOS! But there is one problem though. The game is missing the images of where to go. It makes the game kind of weird, because you don't know what to press on the main menu screen, or how to exit to the main menu. I have tried every version of this game. (There are only 2) But each of them have the same problem. I hope you guys can fix this soon. The reason I run this on the Sonicvrey Patch is because it doesn't run on the regular TouchHLE APK. Here is an example of what I mean by missing images

### By submitting this issue, I certify that…

- [ ] I have tested that this version of this app is at least partially working in a previous version of touchHLE.
- [ ] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [ ] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by iplayfastandfurious** [comment]
![Screenshot_20240927_124802_touchHLE](https://github.com/user-attachments/assets/65231e0d-76a0-4196-a60c-1efffd32ef0e)

![16377185-the-fast-and-the-furious-pink-slip-3d-iphone-main-menu (1)](https://github.com/user-attachments/assets/01eb534f-d01d-4eeb-8f70-b789d07d96e0)


Examples:

**Comment by iplayfastandfurious** [comment]
I found out that TouchHLE sonicvrey is unofficial. (I don't know how did I not realize that) Anyways, you can delete this issue

**Comment by hikari-no-yume** [comment]
I am curious what the problems you experience on the official touchHLE are? You can get the latest official trunk/preview build at https://touchhle.org/download/

**Comment by iplayfastandfurious** [comment]
Thank you for the latest official version! The problem I experience with the game is when I try to run it, it crashes. I used all the versions but none of them work

**Comment by hikari-no-yume** [comment]
I see. As I understand it, there might be a larger number of games that partially work on SonicVrey's fork. However, the code quality in that fork is incredibly low, so it does not surprise me that there would be strange issues. Also, there is a lot of code plagiarised from the work of ciciplusplus (copied without credit) among others, so we are generally not very happy about this fork and would rather people don't use it.

Thanks for filing the issue.
