### ISSUE TITLE
.app bundles dont work

### ISSUE THREAD

**Issue by NewthanGuy** [hikari-no-yume/touchHLE#375]
### Describe the feature or issue.

.app bundles dont seem to work in touchHLE
touchHLE crashes and does not load when theres an .app bundle in touchHLE_apps with
thread 'main' panicked at src/bundle.rs:103:19:
IndexMap: key not found

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
This isn't enough information. What app specifically? Is it one that has a star rating in the app compatibility database?

**Comment by NewthanGuy** [comment]
well it seems to be any .app bundles while testing

**Comment by hikari-no-yume** [comment]
Well, it works for me. But I am not testing the same apps as you, clearly.

**Comment by NewthanGuy** [comment]
well i was testing .pxl apps's .app bundles since i was curious if they worked

**Comment by hikari-no-yume** [comment]
I tested again, .app bundles still work fine:

<img width="592" alt="image" src="https://github.com/user-attachments/assets/12345595-a104-4e7c-ae6b-eb7ca400aeb9">

I think .pxl is a homebrew format used before the launch of the iOS App Store? If so, it is not surprising they don't work, we don't claim any support for iPhone OS 1.x apps.
