### ISSUE TITLE
Zombie Infection regression

### ISSUE THREAD

**Issue by HunterGM360** [hikari-no-yume/touchHLE#377]
### App DB report link

https://appdb.touchhle.org/apps/347

### App name

Zombie Infection

### App version

1.0.0

### touchHLE version

v0.2.2-359-g7b1b382

### Operating system

Android

### GPU

Adreno (TM) 640

### What is the problem with the app?

The last preview update saw a regression in Zombie Infection, freezing at the beginning of loading.

### If touchHLE crashed, please paste the log output.

```text
[log.txt](https://github.com/user-attachments/files/17534935/log.txt)
```

### By submitting this issue, I certify that…

- [x] I have tested that this version of this app is at least partially working in a previous version of touchHLE.
- [x] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
I just checking latest APK build on my phone and Zombie infection is working as expected.

What is the last known version of trunk builds to work on your side? Do you have logs from that version?

**Comment by HunterGM360** [comment]
I think I've found the cause of this, I deleted the saves from the game folder and it did work.
Probably they got corrupted, but I have no idea why this happened.
