### ISSUE TITLE
Why does so many apps that are supported keep crashing 

### ISSUE THREAD

**Issue by Darksoulzz9** [hikari-no-yume/touchHLE#379]
### Describe the feature or issue.

So many games that I try to open keeps crashing for no reason. I don't know what the problem is, For Example: COD WaW Zombies and many other games aren't opening 

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
> For Example: COD WaW Zombies and many other games aren't opening

Where did you read that this game is supported?

**Comment by ciciplusplus** [comment]
Post a crashlog.

You're either using a wrong version of touchHLE or a wrong version of an app.

**Comment by hikari-no-yume** [comment]
Closing for now. I may reopen this if you can demonstrate that you're having this problem in a supported app.
