### ISSUE TITLE
Fat Binary Support

### ISSUE THREAD

**Issue by Sumb0o** [hikari-no-yume/touchHLE#38]
It would be nice if Fat Binary was supported for this.

**Comment by hikari-no-yume** [comment]
Oh, could you clarify the request a bit? Do you mean you want the emulator to support iPhone OS/iOS apps that are fat binaries (ARMv6/ARMv7/ARMv8 I guess), or that you would like an Apple Silicon build of the emulator? Both are fat binaries, haha.

**Comment by hikari-no-yume** [comment]
Just to avoid clutter, I'll close this until I get a response, okay?

**Comment by hikari-no-yume** [comment]
Replaced by https://github.com/hikari-no-yume/touchHLE/issues/50.
