### ISSUE TITLE
Confusion of equality methods (isEqualTo: vs isEqual:)

### ISSUE THREAD

**Issue by ciciplusplus** [hikari-no-yume/touchHLE#390]
### Describe the feature or issue.

Right now we use isEqualTo: in the NS part of the codebase to test for equality, but we should use isEqual: instead.

According to https://nshipster.com/equality/, isEqualTo: is a category method of NSScriptWhoseTests

A tentative fix is currently under review https://review.gerrithub.io/c/touchHLE/touchHLE/+/1204407

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
@ciciplusplus Is this fixed as of https://github.com/touchHLE/touchHLE/commit/560b49b9ca27434c5b24c019ff8307be019580eb?

**Comment by ciciplusplus** [comment]
Yeap fixed!
