### ISSUE TITLE
Confusion with the trunk builds

### ISSUE THREAD

**Issue by JuanDaBoi** [hikari-no-yume/touchHLE#391]
### Describe the feature or issue.

idk how i download one of the preview builds...

### By submitting this issue, I certify that…

- [ ] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [ ] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
https://touchhle.org/download/

**Comment by JuanDaBoi** [comment]
nvm i downloaded it
