### ISSUE TITLE
Apps not showing

### ISSUE THREAD

**Issue by JuanDaBoi** [hikari-no-yume/touchHLE#392]
### Describe the feature or issue.

when i try to put an ipa file its just get stuck in the:
No apps we're found in storage/emulated/0/Android/data/org.touchhle.android/files.

please fix this.
![Captura de pantalla_20241126-194924](https://github.com/user-attachments/assets/088de67b-fcb8-4ca3-a4ec-11c1fa1be1d9)

### By submitting this issue, I certify that…

- [ ] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [ ] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
Remove the files and use a different file manager to move them again https://play.google.com/store/apps/details?id=com.marc.files&hl=en

this should help

**Comment by JuanDaBoi** [comment]
fixed, thank u.
