### ISSUE TITLE
Alright, guess what.

### ISSUE THREAD

**Issue by JuanDaBoi** [hikari-no-yume/touchHLE#394]
### Describe the feature or issue.

guess what, if ciciplusplus itself completes on ios 4.0 apps.

then why not support falling fred, running fred, or other games from dedalord?

NOTE THAT THIS IS NOT A REQUEST.

### By submitting this issue, I certify that…

- [ ] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [ ] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
read the FAQ https://touchhle.org/faq.html

**Comment by JuanDaBoi** [comment]
yeah Yeah YEAH. idc

**Comment by ciciplusplus** [comment]
@JuanDaBoi please stop spamming here, thanks.
