### ISSUE TITLE
No mouse/trackpad option for tilt controls

### ISSUE THREAD

**Issue by eisnerguy1** [hikari-no-yume/touchHLE#4]
So, I've got a 2015 MacBook Pro running 12.6.2. I'm trying to use my trackpad mouse and Super Monkey Ball isn't recognizing it as a mouse. Does the game only work with a physical mouse? Either way, thank you for helping to preserve old iOS games! 😄 👍🏻

**Comment by hikari-no-yume** [comment]
Hi, sorry, I need to clarify the README a bit: currently a game controller is the only option for the tilt controls; a mouse/touchpad can only be used for the touch input.

You're not the first person to trip up on this. I think I could try to add mouse support, but I'm not sure it'll be a good experience.

**Comment by eisnerguy1** [comment]
Ah, that makes sense. I'll give it a shot this weekend. Thanks again!

**Comment by hikari-no-yume** [comment]
I made the README a bit clearer (the copy in this GitHub repo). I'll keep this open as a reminder that I should experiment with mouse-based accelerometer simulation. I'm thinking I could use the right mouse button for tilt controls, and the left mouse button for touch inputs. I guess that might be good enough for Super Monkey Ball and some other entirely tilt-control-based games.

**Comment by hikari-no-yume** [comment]
I have been reminded that some of the Super Monkey Ball arcade machines used trackballs. I wonder...

**Comment by hikari-no-yume** [comment]
Hey, @alborrajo actually implemented this in 6986dd684d544ea181a74f0a961f1aa5cf8fb9d6 and it makes Super Monkey Ball playable on PC, it's not perfectly comfortable but it's still fun!
