### ISSUE TITLE
Assertion Failed error when launching Monkey Ball

### ISSUE THREAD

**Issue by icup321** [hikari-no-yume/touchHLE#40]
I tried running Monkey Ball (all versions) on Windows following the instructions as exactly stated, but when I launch the game, it opens and shows a splash screen for a split-second, then immediately closes. I compared it with another user's error log and I seem to be getting an assertion failure error of some sort, could anyone look into this?
[message.txt](https://github.com/hikari-no-yume/touchHLE/files/10611819/message.txt)

**Comment by hikari-no-yume** [comment]
I'm assuming this is your error log?

This is an interesting case. For the benefit of others, this is the key part:

```
thread 'main' panicked at 'assertion failed: gl::GetError() == 0', src\window\gl.rs:201:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Register state immediately after panic:
         R0: 0x3000b2f0  R1: 0x30009570  R2: 0x00000003  R3: 0x00000000
         R4: 0x0004ed84  R5: 0x0004edec  R6: 0x3000b2f0  R7: 0xffffff0c
         R8: 0x00000000  R9: 0x00000000 R10: 0x00000000 R11: 0x3000b480
        R12: 0x0004d274  SP: 0xfffffecc  LR: 0x00026451  PC: 0x0003f950
Attempting to produce stack trace for main thread:
 0. 0x3f950 (PC)
 1. 0x26451 (LR)
 2. [host function]
 3. 0x0
Next FP (0x0) is outside the stack.
```

So the OpenGL driver is returning an error at some point. If it's gotten that far it's probably an un-corrupted, known-working version of Super Monkey Ball, and judging by the addresses in the stack trace this is Super Monkey Ball 1.3, which definitely should work.

I'm going to guess something is unusual about your computer. Could you tell me:

* What version of Windows are you using?
* Have you installed the latest graphics drivers from your graphics card provider? (NVIDIA, AMD or Intel, usually)?
* What graphics card do you have, if any? Brand (NVIDIA, AMD, Intel) and model number (e.g. GTX 1080).
* What CPU do you have?
* Do you have anything installed that applies an in-game overlay? Steam, Discord and various other software targeted at gamers often has this. If you disable all of these you're aware of, is it fixed?
* Uh, is there anything unusual about your computer setup? Very high refresh rate monitor for example?

**Comment by icup321** [comment]
I figured it out now, I was running Rivatuner Statistics in the background with FPS display overlay and that somehow causes the emulator window to close.

**Comment by hikari-no-yume** [comment]
Oh wait I didn't look carefully enough, it's actually crashing at the end of displaying the splash screen (`display_splash()` in `gl.rs`), so it's not even getting through startup. I think this is happening when the game tells touchHLE it should be displayed in landscape. When that happens, touchHLE re-draws the splash screen rotated.

**Comment by hikari-no-yume** [comment]
> I figured it out now, I was running Rivatuner Statistics in the background with FPS display overlay and that somehow causes the emulator window to close.

Aha, that makes sense. Unfortunately the way apps like that work is they basically inject themselves into games (or touchHLE in this case) and run a bunch of commands, and if they're not very carefully written, they can mess things up. I guess that's what happened here.

If someone else hits the same thing, I can add a note to the README that Rivatuner Statistic Server is incompatible.

**Comment by hikari-no-yume** [comment]
Shame that it's RTSS of all things, I like that software. Oh well…

Thanks for the report!

**Comment by hikari-no-yume** [comment]
I realised this is unlikely to be the last issue of its kind, so I added a note to the README in c89945a1292617c9ab52a38b2faac96d6645aa2c.

**Comment by hikari-no-yume** [comment]
I tried out RTSS with touchHLE on my PC (which has an NVIDIA GTX 1070) and I couldn't get it to crash, so maybe it's an issue with a particular graphics vendor, an outdated version of RTSS, or something else.

However, I did discover that RTSS is effectively incompatible with touchHLE anyway: the statistics show up while on the app's launch image/splash screen, but don't appear while in-game, so there's no point trying to use it with it.
