### ISSUE TITLE
[Suggestion] to Add Tags for Improved Visibility and Discoverability

### ISSUE THREAD

**Issue by Ahmadjerj** [hikari-no-yume/touchHLE#402]
### Describe the feature or issue.

I had a bit of trouble finding this repo despite searching on both Google and GitHub. Even projects like ipasim, which are less functional, showed up higher in search results. I actually found this project through the ipasim repo, not directly via search.

To help improve discoverability, I wanted to suggest adding the following tags:

    iOS Emulation
    iOS Frameworks
    Jailbreak
    Game Emulation
    iOS 2-3 Emulation
    Emulator
    iOS Development

I’m sorry to open an issue and I don’t want to be a bother, but I think these tags could really help others find the project more easily. Keep up the great work, and thanks for considering this! Sorry if I was being noisy.

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
I don't want to market the “repo”, just the emulator itself, and I don't think most of these “tags” are things people actually search GitHub for? The project is enough of a success that any SEO problem will eventually fix itself. I feel kind of dirty about keyword stuffing.
