### ISSUE TITLE
I've disabled repository interactions for a while so I can take a break

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#42]
Sorry for the inconvenience. If you want to contribute something, be it a pull request or an issue, please hold on to it and come back in a few days. I haven't taken a serious break since the start of the project and need to rest a bit.

Thanks for your understanding.

**Comment by hikari-no-yume** [comment]
OK, over now, sorry for the inconvenience!

**Comment by upintheairsheep** [comment]
Yay
