### ISSUE TITLE
Support for built-in accelerometers in phones and similar devices

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#45]
There is a sister issue for supporting accelerometers in game controllers: https://github.com/hikari-no-yume/touchHLE/issues/13

We can probably get away without updating SDL2 for this issue, but it will be more difficult to test because there's no Android port yet.

**Comment by hikari-no-yume** [comment]
Huh, I have been told that the Steam Deck's accelerometer doesn't show up in this way, it shows up as if it's attached to a Steam Controller or something. Okay.

**Comment by puckipedia** [comment]
The only supported device sensors by upstream SDL right now are the PS Vita, iOS/Android, the Nintendo 3DS, and Windows (which I suspect at least covers any 360/hybrid-tablet laptop, and possibly more.)

**Comment by hikari-no-yume** [comment]
It would be funny to run this on a Windows Phone 10 device.

**Comment by hikari-no-yume** [comment]
I guess I forgot to close this issue, I implemented this in 15a960102f3db6fe60948e72ff6e567128f32bad.
