### ISSUE TITLE
Need help, app won't run.

### ISSUE THREAD

**Issue by Zai603** [hikari-no-yume/touchHLE#47]
I'm trying to open an app called Rhythm Thief & the Paris Caper; it boots up for a second, closes, and gives me this message in PowerShell:

**touchHLE::mach_o: Warning! DyldInfo is not handled.
touchHLE: Warning: app binary depends on unexpected dylib "/usr/lib/libiconv.2.dylib"
Error: "Mach-O file has no 'start' symbol, perhaps it is not an executable?"**

I really don't know what this means, but if anyone does, I would appreciate some help!

**Comment by hikari-no-yume** [comment]
Hi, these are the kinds of error messages I'd expect to see for a newer app that uses features we don't support yet. As the README says, only one app is known to work right now. I don't know if or when your app will work, sorry.

**Comment by Zai603** [comment]
I see, thanks!

**Comment by hikari-no-yume** [comment]
As an aside, I googled that app and it seems like it relied on online services, so even if you could get it running, I guess you wouldn't be able to get past the title screen, unless you could hack the game to not need an internet connection.

**Comment by upintheairsheep** [comment]
> As an aside, I googled that app and it seems like it relied on online services, so even if you could get it running, I guess you wouldn't be able to get past the title screen, unless you could hack the game to not need an internet connection.

or wait even longer for internet support to be added, which might not even happen
