### ISSUE TITLE
Sharing some logs you may find helpful

### ISSUE THREAD

**Issue by WumboSpasm** [hikari-no-yume/touchHLE#5]
Thanks for creating this project first of all. I tested touchHLE with a collection of around 1,000 outdated/abandonware apps from the iPhone OS 2.x era and redirected the logs to text files for your convenience.

As to be expected, nearly every app either refuses to load outright or crashes the emulator shortly after startup. The only exceptions are Super Monkey Ball (obviously) and Dungeon and Hero, which freezes at the Chillingo logo and only crashes once the game window is clicked.

I'll probably update this issue with new logs whenever there's an update. Looking forward to the future of the project.

[Logs.zip](https://github.com/hikari-no-yume/touchHLE/files/10581702/Logs.zip)

**Comment by hikari-no-yume** [comment]
Oh, thanks! I'll have a look at this at some point. I'm closing the issue just so it doesn't contribute to the open issues count.

Incidentally, how quickly did that go? Just a few minutes?

**Comment by WumboSpasm** [comment]
It only took around 10 minutes, yeah.

**Comment by hikari-no-yume** [comment]
If you feel like it, it would be nice to know how it looks for v0.1.1. Maybe one or two apps I don't know about are suddenly working.

**Comment by WumboSpasm** [comment]
I just ran through them again. Nothing works except for Crash Nitro Kart and Super Monkey Ball, and Dungeon and Hero now crashes upon load rather than freezing. However, most games *at the very least* boot now, and some even stick around for a second or two before crashing.

[Logs.zip](https://github.com/hikari-no-yume/touchHLE/files/10774976/Logs.zip)

**Comment by hikari-no-yume** [comment]
Thanks!

**Comment by 27hectormanuel** [comment]
Could we get Spy Mouse working?

**Comment by WumboSpasm** [comment]
Here's the updated logs for v1.2. Not much to say about it other than it seems like more games are sticking around for longer before crashing.

[Logs.zip](https://github.com/hikari-no-yume/touchHLE/files/10915452/Logs.zip)
