### ISSUE TITLE
Fat binary (ARMv6 + ARMv7) support

### ISSUE THREAD

**Issue by Sumb0o** [hikari-no-yume/touchHLE#50]
Hello, after seeing your comment i am here to confirm i actually want the emulator to support iPhone OS/iOS apps that are fat binaries. I could've done that sooner but i really wasn't able to do so. ig here you go lol

**Comment by hikari-no-yume** [comment]
For others' context, this discussion began in https://github.com/hikari-no-yume/touchHLE/issues/38.

Okay, sure, eventually there'll be fat binary support I guess. I would expect however that apps which won't load for this reason are also going to have other compatibility problems, at least for the time being.

**Comment by nitinseshadri** [comment]
FYI: On a Mac with Xcode or the Command-Line Tools installed, you can use `lipo` to extract the armv6 slice from a fat binary as such:

`lipo -thin armv6 <path/to/fat-binary> -o <output-path>`

You can also check what slices are in a fat binary using `lipo -info <path/to/binary>`.

This could be a useful workaround for the time being.

**Comment by jet082** [comment]
Okay just as an update for those who come here in future:

You can do get around this with regular Linux (even on Windows via WSL) by using [llvm-lipo](https://github.com/llvm/llvm-project) as such:

```
llvm-lipo -thin armv6 falcon/Payload/StarWars-FalconRun.app/StarWars-FalconRun -o falcon/Payload/StarWars-FalconRun.app/StarWars-FalconRun.out
```

Then rename the .out to the original file and you can bypass the ``Fat binary support is not implemented yet`` error.

**Comment by hikari-no-yume** [comment]
Oh nice!

FWIW I will of course implement fat binary support at some point, but I don't think I've come across an iPhone OS 2.x title that needs it, so I doubt any of these apps will actually work even if you use something like `llvm-lipo`. I'm not sure when fat binaries became the norm on iOS, but I'm guessing I'll have to implement this once I get around to iPhone OS 3.x or iOS 4.x.

(If you do find an iPhone OS 2.x game that uses this, please tell me!)

**Comment by jet082** [comment]
Is there a way to easily tell the iOS version? I'm guessing the ones I've been testing must be 3.x since they're released early in 2010.

**Comment by hikari-no-yume** [comment]
I recently added some code that makes touchHLE print out the “minimum OS version” info from an app when you run it, but it's not in one of the releases yet. I'm hoping to push that out sometime this week, maybe even today if I'm lucky, so stay tuned I guess.

If you are impatient, you might want to find a tool that can read Apple plist files (allegedly iTunes for Windows might ship with one… is that true? on macOS it's called `plutil`) and check the `MinimumOSVersion` key in the `Info.plist` file.

**Comment by hikari-no-yume** [comment]
Oh yeah, this might be obvious, but the version requirements for an app often change with updates. If you can somehow obtain an older version of an app, it have different requirements.

Also FWIW I personally expect iPhone OS 3.x is going to be no big problem to support, once I get round to it. At least iPhone OS 3.0 and 3.1. iPhone OS 3.2 scares me a bit.

**Comment by jet082** [comment]
The new version prints out the minimum version perfectly! The earliest app I have with a fat binary is iOS 3.0 (Zenonia 2 v1.9).

**Comment by hikari-no-yume** [comment]
Thanks for testing! Now that I think about it and do a little research, I think the first iOS device that could benefit from fat binaries (i.e. supported ARMv7, not just ARMv6) was the iPhone 3GS, and that came out in 2009 and ran iPhone OS 3 at launch… so it must be the case that fat binaries are for iPhone OS 3 and onwards. I guess I'll do this then once I have iPhone OS 3 apps working to some degree.

**Comment by GlitchyPSIX** [comment]
I have another game called 3D BrickBreaker Revolution which was also for iPhone 3GS and it is indeed a fat binary. I will be trying lipo to see if there are any other compatibility issues.

**Comment by hikari-no-yume** [comment]
Just stumbled upon this note in [an old Apple developer Q&A](https://developer.apple.com/library/archive/qa/qa1760/_index.html#//apple_ref/doc/uid/DTS40011826):

> Note: Set the iOS Deployment target to 4.3 or later in your project if you wish to drop armv6 support for your application. An armv7 processor is required to run versions of iOS later than 4.2.1.

Looks like always using the ARMv6 version will get us quite far.

**Comment by lentas1** [comment]
minecraft pe not working on windowss builsd because fat support is missing

**Comment by hikari-no-yume** [comment]
Fat binary support is merged as of yesterday. :) 0685d0b1e25ec95d0ad6405385f87479847e89c6

Bear in mind though that fat binaries are always for iOS 3.0 or later, and touchHLE still doesn't have proper support for that version. I'm planning to improve that soon though.
