### ISSUE TITLE
Could not read icon file

### ISSUE THREAD

**Issue by ejrv** [hikari-no-yume/touchHLE#54]
Could not read icon file
![image](https://user-images.githubusercontent.com/67105391/218329040-5364bbaf-47f8-4036-aa8e-8da89a1f292e.png)
sorry if im being a idiot but why this happens

**Comment by DartPower** [comment]
Try to find any icon in folder or create any image png (92x92 maybe) and copy to "Icon.png"

**Comment by hikari-no-yume** [comment]
Hi, this is a known issue that I need to fix. An icon file being missing shouldn't stop the emulator from starting, it's just cosmetic after all.

But bear in mind that only one app is known to work right now, so even if this was fixed, your app probably won't work for various other reasons.

**Comment by ejrv** [comment]
okay thanks for the info

**Comment by ejrv** [comment]
are you planning on making the springboard too? (home screen)

**Comment by hikari-no-yume** [comment]
@ejrv: https://github.com/hikari-no-yume/touchHLE/issues/28

**Comment by upintheairsheep** [comment]
> are you planning on making the springboard too? (home screen)

there is a QEMU fork emulating the iPod Touch 1 for that, TouchHLE won’t support springboard for legal reasons

**Comment by upintheairsheep** [comment]
> Hi, this is a known issue that I need to fix. An icon file being missing shouldn't stop the emulator from starting, it's just cosmetic after all.
> 
> But bear in mind that only one app is known to work right now, so even if this was fixed, your app probably won't work for various other reasons.

If an icon cannot be found, it should just show the touchHLE logo

**Comment by hikari-no-yume** [comment]
Sure, something like that.

**Comment by ejrv** [comment]
any updates? lol

**Comment by hikari-no-yume** [comment]
Please read [the contributing guide](https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md).
