### ISSUE TITLE
unimplemented function _wctob'

### ISSUE THREAD

**Issue by DartPower** [hikari-no-yume/touchHLE#58]
thread 'main' panicked at 'Call to unimplemented function _wctob', src\dyld.rs:474:9

This function uses by very many software and games and i think:
This function hard to implement like the stub for example.. or more "real"?

P.S. Sorry for my bad english 😄

**Comment by RealSupremium** [comment]
Looks like it's a simple wide char to byte char conversion. There is also btowc too.
https://man7.org/linux/man-pages/man3/wctob.3.html
https://man7.org/linux/man-pages/man3/btowc.3.html

**Comment by TylerJaacks** [comment]
@RealSupremium could you try my pull request https://github.com/hikari-no-yume/touchHLE/pull/69 and see if that fixes ur issue.

**Comment by hikari-no-yume** [comment]
They aren't the one who reported the issue, why are you pinging them?

In any case, to save someone else some time: that pull request won't work.

**Comment by hikari-no-yume** [comment]
Implemented this function in 5da6751c51bbe13d3d60ca21fc3d6975208529ba.

Bear in mind that the app you want to run is probably still going to be broken for other reasons, though.
