### ISSUE TITLE
Cannot run on macOS

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#59]
So I tried running Monkey Ball on touchHLE with an M1 MacBook and this is what it always says:
`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10661 "(null)" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}
`
This doesn't appear on my Windows PC trying to run the exact same app.

**Comment by hikari-no-yume** [comment]
That's… weird. Can you right-click on the touchHLE executable in Finder and click Open? What happens then?

**Comment by ghost** [comment]
This is what it says:
<img width="893" alt="Screenshot 2023-02-15 at 6 24 41 AM" src="https://user-images.githubusercontent.com/86171223/219054625-f06359e5-e14b-4775-84aa-83b54ea8fa49.png">

**Comment by hikari-no-yume** [comment]
Okay, if you try to use touchHLE again to run an app, does it work now? The process of running it that way may have bypassed the Gatekeeper system, which might have been the original problem.

**Comment by hikari-no-yume** [comment]
I'm closing this to unclutter things since I'm assuming your issue was resolved, but if not,  I'm happy to re-open this.

**Comment by ghost** [comment]
Now it gets confused if it's installing on my MacBook.
<img width="467" alt="Screenshot 2023-02-20 at 3 11 05 PM" src="https://user-images.githubusercontent.com/86171223/220211281-33b25602-3d45-4629-a9e7-e5c09d0fa2a9.png">
I ran it with the command `open touchHLE "Monkeyball.ipa`

**Comment by hikari-no-yume** [comment]
If you write `open A B` it will open two apps, A and B. touchHLE is a command-line app, you need to write `./touchHLE 'Monkey Ball.app'`.

**Comment by ghost** [comment]
Extracted the "app" file, now it says:
`Error: "Could not open app bundle: Monkey Ball.app is not a directory or an IPA file"`
So @hikari-no-yume is likely the only person that can actually run touchHLE on macOS without this error.

**Comment by ghost** [comment]
I will no longer download touchHLE for macOS until a GUI is implemented

**Comment by hikari-no-yume** [comment]
> Extracted the "app" file, now it says: `Error: "Could not open app bundle: Monkey Ball.app is not a directory or an IPA file"`

Uh… I've no idea what you did, but you shouldn't be getting that error. You don't need to extract the `.app` file though, `./touchHLE 'Monkey Ball.ipa'` should be fine, assuming you've actually named the IPA file `Monkey Ball.ipa` and it's in the current directory.

> So @hikari-no-yume is likely the only person that can actually run touchHLE on macOS without this error.

Many people have gotten this working on Windows, and I know of at least one other person who's gotten it running on macOS.

> I will no longer download touchHLE for macOS until a GUI is implemented

I'm sorry to hear you're having a bad time.
