### ISSUE TITLE
Could not load executable: Executable is not for an ARM CPU!

### ISSUE THREAD

**Issue by pbz134** [hikari-no-yume/touchHLE#6]
![Unbenannt](https://user-images.githubusercontent.com/53271427/216690085-a59d6aec-afdd-445b-b79d-c3e7c83e4cf5.PNG)

**Comment by hikari-no-yume** [comment]
Sorry, without knowing _which_ app this is, I can't tell if this is some weird bug, or if this is simply the expected behaviour (the emulator only supports ARM apps).

**Comment by hikari-no-yume** [comment]
I had a look at the code, and apparently AArch64 is classified as a separate “CPU type” to 32-bit ARM. So the problem is presumably that you're trying to run a 64-bit app. This project does not try to support 64-bit apps. I tried to make that clear in the README.
