### ISSUE TITLE
Bleeding edge or nightly builds

### ISSUE THREAD

**Issue by childishbeat** [hikari-no-yume/touchHLE#60]
May I suggest bleeding edge or nightly builds, e.g. on AppVeyor? Many good emulators have them, and it would be nice not to have to wait for improvements in new stable versions, like IPA support. It would also ensure any issues filed aren't fixed in the latest or close to latest source code.

**Comment by hikari-no-yume** [comment]
At the current rate of development, I'm probably going to have a new release at least once a month (this month it'll be two), so it's not going to be a long wait I think. Also, I've tried to make this project easy to build yourself if you want.

With that said… I probably should set up a continuous integration system for this eventually.

**Comment by childishbeat** [comment]
I did try, but I failed 'cause I'm a noob and decided it wasn't worth it. If you could make the building instructions more specific for newbies, that would be nice.

Now that I'm over it, I'd like to try again, partly to try out IPA support.

**Comment by upintheairsheep** [comment]
Some random thought I have, but maybe touchHLE will be forked into another project called "touchHLE64" in the future which plans to support 64-bit apps, and possibly gets sued by Apple at one point where it runs current apps which Apple loses.

**Comment by hikari-no-yume** [comment]
@upintheairsheep Please try to keep discussion on-topic.

**Comment by hikari-no-yume** [comment]
Hmm, what build issues did you run into?

**Comment by hikari-no-yume** [comment]
As of 6a1937bc186152841195aeef579876368a458ca0 (thanks to @dylanpdx in https://github.com/hikari-no-yume/touchHLE/pull/93), there's a “GitHub action” that should produce Windows x64 and macOS x64 builds for each new commit to trunk. Note that the builds only contain the pure binary, so you'll need to grab the fonts, dylibs and default settings files from a previous release or from git.
