### ISSUE TITLE
sysctl customization "iPhone1,1", etc

### ISSUE THREAD

**Issue by upintheairsheep** [hikari-no-yume/touchHLE#61]
Please make a flag in the future to change the device string spoofed by sysctl. This is useful for bypassing incompatibility messages in the future, or getting different screen sizes as well.

**Comment by hikari-no-yume** [comment]
Uhm… this is obviously a desirable thing, but it's really weird to have issues opened that suggest future improvements to features we do not have. There is no sysctl right now, I don't even know what that is.

**Comment by upintheairsheep** [comment]
Random question, can we use ChatGPT to contribute code or can we not?

**Comment by hikari-no-yume** [comment]
Well, large language models like that tend to have absorbed various source code publicly available on the internet, and this puts you at risk of violating copyright, as noted in the [contributing guidelines](https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md). But if you:

* can convince yourself that the ChatGPT output is perfectly original;
* understand exactly what every line of code you are contributing does, how it does it, and why it is necessary;
* have thoroughly tested the code;
* think it meets the quality standards of the project; and
* are able to make improvements in response to code review

then in theory I have no objection to contributing it.

If you can't do all that, then no.

**Comment by hikari-no-yume** [comment]
Actually, considering the copyright risk, I'm going to make that a hard “no”. The same applies to GitHub Copilot and similar tools.

**Comment by upintheairsheep** [comment]
> Actually, considering the copyright risk, I'm going to make that a hard “no”. The same applies to GitHub Copilot and similar tools.

Make sure to add it to the contribution guide as well.
