### ISSUE TITLE
Per-app settings, including defaults

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#67]
Let's say we have two files, `touchHLE_default_settings.txt` and `touchHLE_settings.txt`. The former would be bundled with the emulator and contain default settings for particular apps, something like:

```
# These are default per-app settings provided by touchHLE.
# We recommend editing the touchHLE_settings.txt file instead of this one.
com.ooi.supermonkeyball: --y-tilt-offset=24
com.vgmobile.cnk2: --landscape-left
```

Then you could create a `touchHLE_settings.txt` file (maybe touchHLE could create it for you when you first run it) to contain per-app overrides and global settings:

```
# These are your personal per-app settings for touchHLE.
# Each line begins with the bundle identifier for that app, followed by a colon, then a list of command-line arguments.
# If you specify settings for an app in this file, the settings in touchHLE_default_settings.txt will not be used.
# For settings that should apply to all apps, put those on a line with an asterisk (*) instead of a bundle identifier.
# You can use a hash sign (#) to add comments: the part of a line following a hash sign is ignored.
*: --scale-hack=3
com.ooi.supermonkeyball: --y-tilt-offset=22
```

**Comment by hikari-no-yume** [comment]
Maybe the `touchHLE_settings.txt` file could include a copy of the `--help` output as comments. This would be helpful for users who aren't familiar with the command line.

**Comment by childishbeat** [comment]
You'd be able to directly open IPA files in touchHLE by default with your preferred settings. No script required. 😊
