### ISSUE TITLE
Add to WinGet repository

### ISSUE THREAD

**Issue by upintheairsheep** [hikari-no-yume/touchHLE#70]
https://github.com/microsoft/winget-pkgs - Please add all versions of touchHLE to winget, it would vastly improve the difficulty of installation.

**Comment by upintheairsheep** [comment]
Now instead of having a folder in the downloads folder, that does get annoying, you will just type "winget install touchHLE" or something like that, and it will start to install it.

**Comment by hikari-no-yume** [comment]
Is something about installing it difficult right now? You just download the zip file and extract it somewhere. You can't install it to Program Files but I don't think that's necessary.

**Comment by upintheairsheep** [comment]
I already installed it, but I believe the package manager would make it more discoverable

**Comment by hikari-no-yume** [comment]
@upintheairsheep You are currently responsible for ~20% of all issues and pull requests that have been filed on this repository and it's taking up a lot of my time. I appreciate your enthusiasm but please slow down. Eventually I might have to block you, which would be unfortunate for the both of us.

**Comment by upintheairsheep** [comment]
I’ll do it myself

**Comment by p0008874** [comment]
I'm pretty sure winget dosen't know how to unzip the file. (Like Scoop did)
So yeah not much you can really do.

**Comment by hikari-no-yume** [comment]
It looks like newer versions support ZIP files actually.

**Comment by upintheairsheep** [comment]
I will only make simple issues for welcome improvements that don't make a lot of work, like this. Additionally, a nice suggestion would be a command line warning when running apps made for iPhoneOS 3 or above.

**Comment by hikari-no-yume** [comment]
> I will only make simple issues for welcome improvements that don't make a lot of work, like this.

Okay. Thanks.

> Additionally, a nice suggestion would be a command line warning when running apps made for iPhoneOS 3 or above.

Ah yeah thanks for pointing that out, I think I know how I could check for this.

**Comment by hikari-no-yume** [comment]
@upintheairsheep Implemented that now: 736a194691077b1767a35f25e376163318aeb4aa

**Comment by upintheairsheep** [comment]
> @upintheairsheep Implemented that now: [736a194](https://github.com/hikari-no-yume/touchHLE/commit/736a194691077b1767a35f25e376163318aeb4aa)

You should kinda make some sort of “mini issue megathread” for small stuff like this

**Comment by hikari-no-yume** [comment]
Not a bad idea but I think it'd quickly become unmanageable since GitHub doesn't have proper threading for replies. Also, it being a bit more effort to create a full issue is a feature as far as I'm concerned, because I don't want a huge flood of them.
