### ISSUE TITLE
Tested Apps (non new working, just confirming these)

### ISSUE THREAD

**Issue by oliviaiacovou** [hikari-no-yume/touchHLE#75]
all ios 2 apps, touchHLE built from source, a few apps make it to the splash and simcity is the only one where the focus switches to the window (in macos stage manager mode) <img width="266" alt="image" src="https://user-images.githubusercontent.com/20854744/223215279-01defae9-e532-4658-b97e-e5bf8ae8c076.png">

**Comment by hikari-no-yume** [comment]
I appreciate the enthusiasm, [but:](https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md)

> ## Issues
> 
> Please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about apps that aren't in the supported list, unless you've got it partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.
