### ISSUE TITLE
Full-screen mode

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#80]
No explanation needed for what this is or why you'd want it.

At a technical level it needs similar things to https://github.com/hikari-no-yume/touchHLE/issues/16: we need to be able to decouple the actual on-screen window size from the size of the framebuffer rendered by the app. I'm a bit scared of how messy that might get, the concept of the window size is already heavily overloaded in touchHLE. I'll need to do some thinking about how to make the code comprehensible and maintainable.

**Comment by hikari-no-yume** [comment]
Implemented in 9a3191332f26491da8c20670766b38607ce3e45d.

**Comment by nimanouri644-beep** [comment]
Your app is great but it's not full screen. Usually, it should have been fixed after these updates. The fork versions have the screen but the games don't run. Please add full screen.
