### ISSUE TITLE
iOS/tvOS version

### ISSUE THREAD

**Issue by zboralski** [hikari-no-yume/touchHLE#92]
I am writing to request that you consider porting TouchHLE to iOS and tvOS platforms.

**Comment by hikari-no-yume** [comment]
Please search existing issues before opening a new one.

**Comment by upintheairsheep** [comment]
tvOS support would be kinda weird as iOS is almost completely touch based.

**Comment by hikari-no-yume** [comment]
Wouldn't the existing Windows and macOS support be weird by that criteria?
