### ISSUE TITLE
Driver gameloft crash

### ISSUE THREAD

**Issue by InfamousKnight** [hikari-no-yume/touchHLE#98]
The game opens a window for a split second and then crashes with this long:

sean@sean-ZenBook-UX425UG-Q408UG:~/Downloads$ wine64 touchhle.exe '/home/sean/Downloads/driver-1.1.1/Driver 1.1.1.ipa' 
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
touchHLE v0.1.2-106-gd894487 (git) — https://touchhle.org/

App bundle info:
- Display name: Driver
- Version: 1.1.1
- Identifier: com.gameloft.Driver
- Internal name (canonical): Driver.app
- Minimum OS version: 2.2.1

Warning: Could not open touchHLE_default_options.txt: File not found. (os error 2)
Warning: Could not open touchHLE_options.txt: File not found. (os error 2)

0024:fixme:system:QueryDisplayConfig (00000002 000000000011C7F8 0000000001FB1228 000000000011C800 0000000001FB1278 0000000000000000): semi-stub
0024:fixme:win:RegisterTouchWindow hwnd 0000000000030050, flags 0x3 stub!
0024:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
0068:fixme:imm:ImeSetActiveContext himc 000000000001002E, flag 0 stub!
0024:fixme:imm:ImmReleaseContext (0000000000030050, 0000000000010054): stub
0024:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4
0068:fixme:imm:ImmReleaseContext (0000000000010020, 000000000001002E): stub
0024:fixme:imm:ImeSetCompositionString PROBLEM: This only sets the wine level string
0024:fixme:imm:ImeSetCompositionString Reading string unimplemented
0024:fixme:imm:NotifyIME NI_CLOSECANDIDATE
0024:fixme:imm:ImeSetActiveContext himc 0000000000010054, flag 0x1 stub!
0024:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.RawGameController", {eb8d0792-e95a-4b19-afc7-0a59f8bf759e}, 00000001407FE360): semi-stub
0024:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.ArcadeStick", {5c37b8c8-37b1-4ad8-9458-200f1a30018e}, 00000001407FE368): semi-stub
0024:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.FlightStick", {5514924a-fecc-435e-83dc-5cec8a18a520}, 00000001407FE378): semi-stub
0024:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.Gamepad", {8bbce529-d49c-39e9-9560-e47dde96b7c8}, 00000001407FE380): semi-stub
0024:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.RacingWheel", {3ac12cd5-581b-4936-9f94-69f1e6514c7d}, 00000001407FE390): semi-stub
0024:err:ole:com_get_class_object class {77a1c827-fcd2-4689-8915-9d613cc5fa3e} not registered
0024:err:ole:com_get_class_object no class object {77a1c827-fcd2-4689-8915-9d613cc5fa3e} could be created for context 0x1
thread 'main' panicked at 'Unexpected I/O failure when trying to access real path "touchHLE_dylibs\\libstdc++.6.0.4.dylib": Path not found. (os error 3). This might indicate that files needed by touchHLE are missing, or were moved while i
t was running.', src\fs.rs:309:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0024:fixme:imm:ImeSetCompositionString PROBLEM: This only sets the wine level string
0024:fixme:imm:ImeSetCompositionString Reading string unimplemented
0024:fixme:imm:NotifyIME NI_CLOSECANDIDATE

And yes, I'm using wine. I don't know how to build this on linux.

**Comment by hikari-no-yume** [comment]
> Please bear in mind that there are infinitely many apps that do not work in touchHLE right now, so please don't open issues about apps that aren't in [the supported list](https://github.com/hikari-no-yume/touchHLE/blob/trunk/APP_SUPPORT.md), unless you've got it partially working (e.g. loaded up to the menu but the main game doesn't work). The fact that an app's splash screen (Default.png) shows up doesn't mean it's partially working.

**Comment by hikari-no-yume** [comment]
> `thread 'main' panicked at 'Unexpected I/O failure when trying to access real path "touchHLE_dylibs\libstdc++.6.0.4.dylib": Path not found. (os error 3). This might indicate that files needed by touchHLE are missing, or were moved while it was running.', src\fs.rs:309:19`

Nightly builds of touchHLE don't include the dylibs and fonts. You'll need to grab those from a normal release or somewhere else for a nightly build to work.
